//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_planmantenimiento
    {
    
        public int id { get; set; }
        public int idmodeloano { get; set; }
        public int kilometraje { get; set; }
        public string Descripcion { get; set; }
    
        public virtual anio_modelo anio_modelo { get; set; }
    }
}
