//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion_repuestoa
    {
    
        public string ref_codigo { get; set; }
        public string bodega { get; set; }
        public string ubicaciong { get; set; }
        public string ubicaciona { get; set; }
        public int ubirpto_id { get; set; }
        public string ubirpto_nombre { get; set; }
        public Nullable<int> ubirptoid_licencia { get; set; }
        public System.DateTime ubirptofec_creacion { get; set; }
        public int ubirptouserid_creacion { get; set; }
        public bool ubirpto_estado { get; set; }
        public Nullable<int> ubirptouserid_actualizacion { get; set; }
        public Nullable<System.DateTime> ubirptofec_actualizacion { get; set; }
        public string ubirptorazoninactivo { get; set; }
    }
}
