//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class adecuaciones_peritaje
    {
        public int id { get; set; }
        public Nullable<int> peritaje_id { get; set; }
        public string referencia_codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio_repuesto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string mano_de_obra_id { get; set; }
        public Nullable<decimal> mano_obra_precio { get; set; }
        public string detalle { get; set; }
        public Nullable<int> user_creacion { get; set; }
        public Nullable<decimal> valor_total_adecuacion { get; set; }
        public Nullable<float> pordescuento { get; set; }
        public Nullable<decimal> valordescuento { get; set; }
        public Nullable<float> poriva { get; set; }
        public Nullable<decimal> valoriva { get; set; }
    
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual ttempario ttempario { get; set; }
        public virtual users users { get; set; }
        public virtual icb_encabezado_insp_peritaje icb_encabezado_insp_peritaje { get; set; }
    }
}
