//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda_demos
    {
        public int id { get; set; }
        public Nullable<int> demo_id { get; set; }
        public Nullable<int> asesor_id { get; set; }
        public Nullable<int> tercero_id { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string motivo { get; set; }
        public Nullable<int> ruta { get; set; }
        public string ncliente { get; set; }
        public string nombre { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public Nullable<int> tipo { get; set; }
        public int idbodega { get; set; }
    
        public virtual bodega_concesionario bodega_concesionario { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual users users { get; set; }
        public virtual vdemos vdemos { get; set; }
        public virtual vtiposdemos vtiposdemos { get; set; }
    }
}
