//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class asesor_log
    {
        public int id { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public int usuario_id { get; set; }
        public System.DateTime fecha { get; set; }
        public bool estado { get; set; }
        public int asesor { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public Nullable<System.DateTime> hora_final { get; set; }
        public int status { get; set; }
        public string observacion { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
