//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bancos()
        {
            this.cuentasbancarias = new HashSet<cuentasbancarias>();
            this.formas_pago = new HashSet<formas_pago>();
            this.documentos_pago = new HashSet<documentos_pago>();
            this.documentos_pago1 = new HashSet<documentos_pago>();
            this.documentos_posfechados = new HashSet<documentos_posfechados>();
        }
    
        public int id { get; set; }
        public string Descripcion { get; set; }
        public string cuenta { get; set; }
        public Nullable<float> comision { get; set; }
        public Nullable<float> retencion { get; set; }
        public Nullable<int> nit { get; set; }
        public Nullable<float> retiva { get; set; }
        public Nullable<float> retica { get; set; }
        public string numero_cuenta { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<int> user_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_actualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<int> licencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasbancarias> cuentasbancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formas_pago> formas_pago { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_pago> documentos_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_pago> documentos_pago1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_posfechados> documentos_posfechados { get; set; }
    }
}
