//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja_menor_encab
    {
        public int cjme_id { get; set; }
        public Nullable<int> cjm_id { get; set; }
        public Nullable<int> idencabezado { get; set; }
    
        public virtual caja_menor caja_menor { get; set; }
        public virtual encab_documento encab_documento { get; set; }
    }
}
