//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cambioubicacionveh
    {
        public int id { get; set; }
        public string idvehiculo { get; set; }
        public Nullable<int> idubicanterior { get; set; }
        public Nullable<int> idubicactual { get; set; }
        public System.DateTime fechacambio { get; set; }
        public int iduser { get; set; }
    
        public virtual ubicacion_bodega ubicacion_bodega { get; set; }
        public virtual icb_vehiculo icb_vehiculo { get; set; }
        public virtual ubicacion_bodega ubicacion_bodega1 { get; set; }
        public virtual users users { get; set; }
    }
}
