//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasificacion_cliente
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public int user_creacion { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public Nullable<int> user_actualizacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactividad { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
