//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasificacionTercero
    {
        public int tptercero_id { get; set; }
        public int tercero_id { get; set; }
        public int clasifTercero_id { get; set; }
    
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual icb_tp_tercero icb_tp_tercero { get; set; }
    }
}
