//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas_valores
    {
        public int ano { get; set; }
        public int mes { get; set; }
        public int cuenta { get; set; }
        public int centro { get; set; }
        public int nit { get; set; }
        public decimal saldo_ini { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal saldo_ininiff { get; set; }
        public decimal debitoniff { get; set; }
        public decimal creditoniff { get; set; }
    
        public virtual centro_costo centro_costo { get; set; }
        public virtual cuenta_puc cuenta_puc { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
    }
}
