//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_formas_pago_factura
    {
        public int id_detalle { get; set; }
        public Nullable<int> idencabezado { get; set; }
        public Nullable<int> idformas_pago { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string vaucher { get; set; }
        public Nullable<long> cheque { get; set; }
        public Nullable<decimal> valorRecibido { get; set; }
        public Nullable<int> caja { get; set; }
        public Nullable<decimal> pendiente { get; set; }
    
        public virtual encab_documento encab_documento { get; set; }
        public virtual formas_pago formas_pago { get; set; }
        public virtual icb_caja icb_caja { get; set; }
    }
}
