//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_costos_adicionales_vehiculo
    {
        public long id_detalle { get; set; }
        public string id_vehiculo { get; set; }
        public int id_costo_adicional { get; set; }
        public decimal precio { get; set; }
    
        public virtual costos_adicionales_vehiculo costos_adicionales_vehiculo { get; set; }
        public virtual icb_vehiculo icb_vehiculo { get; set; }
    }
}
