//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_agendamiento
    {
        public int id { get; set; }
        public Nullable<int> fk_agendamiento { get; set; }
        public Nullable<int> fk_encab_documento { get; set; }
        public Nullable<int> fk_recibidotraslado { get; set; }
    
        public virtual agenda_mensajero agenda_mensajero { get; set; }
        public virtual agenda_mensajero agenda_mensajero1 { get; set; }
        public virtual encab_documento encab_documento { get; set; }
        public virtual encab_documento encab_documento1 { get; set; }
        public virtual recibidotraslados recibidotraslados { get; set; }
    }
}
