//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_anulacion
    {
        public int id { get; set; }
        public Nullable<int> motivo { get; set; }
        public Nullable<int> documento { get; set; }
    
        public virtual tp_doc_registros tp_doc_registros { get; set; }
        public virtual motivo_anulacion motivo_anulacion { get; set; }
    }
}
