//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosacruzar
    {
        public int id { get; set; }
        public int idencabrecibo { get; set; }
        public decimal valorrecibo { get; set; }
        public int idencabfactura { get; set; }
        public decimal valorfactura { get; set; }
        public decimal saldo { get; set; }
        public bool cruzado { get; set; }
    
        public virtual encab_documento encab_documento { get; set; }
        public virtual encab_documento encab_documento1 { get; set; }
    }
}
