//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_tercero
    {
        public int id { get; set; }
        public Nullable<int> iddocumento { get; set; }
        public Nullable<int> idtercero { get; set; }
        public string rutadocumento { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<int> userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
    
        public virtual documento_facturacion documento_facturacion { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
