//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento_facturacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento_facturacion()
        {
            this.documentos_tercero = new HashSet<documentos_tercero>();
            this.documentos_vehiculo = new HashSet<documentos_vehiculo>();
            this.icb_tpeventos = new HashSet<icb_tpeventos>();
            this.vdocumentosflota = new HashSet<vdocumentosflota>();
        }
    
        public int docfac_id { get; set; }
        public string docfac_nombre { get; set; }
        public Nullable<int> docfacid_licencia { get; set; }
        public System.DateTime docfacfec_creacion { get; set; }
        public int docfacuserid_creacion { get; set; }
        public Nullable<System.DateTime> docfacfec_actualizacion { get; set; }
        public Nullable<int> docfacuserid_actualizacion { get; set; }
        public bool docfac_estado { get; set; }
        public string docfacrazoninactivo { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_tercero> documentos_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_vehiculo> documentos_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_tpeventos> icb_tpeventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vdocumentosflota> vdocumentosflota { get; set; }
    }
}
