//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaProforma
    {
        public int id { get; set; }
        public int idPedido { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public Nullable<decimal> valorSolicitado { get; set; }
        public string observaciones { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<int> userid_actualizacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public int dirigido { get; set; }
    
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual vpedido vpedido { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
