//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_insp_peritaje
    {
        public int insp_id { get; set; }
        public int insp_zona_id { get; set; }
        public int insp_pieza_id { get; set; }
        public int insp_conve_id { get; set; }
        public string insp_comentario { get; set; }
        public int insp_encabezado_id { get; set; }
    
        public virtual icb_conveperitaje icb_conveperitaje { get; set; }
        public virtual icb_encabezado_insp_peritaje icb_encabezado_insp_peritaje { get; set; }
        public virtual icb_piezaperitaje icb_piezaperitaje { get; set; }
        public virtual icb_zonaperitaje icb_zonaperitaje { get; set; }
    }
}
