//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_sysparameter_log
    {
        public int paramlog_id { get; set; }
        public string paramlog_valor { get; set; }
        public string paramlog_descripcion { get; set; }
        public int paramlog_usuario { get; set; }
        public System.DateTime paramlog_fecha { get; set; }
    }
}
