//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_encabezado_insp_peritaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_encabezado_insp_peritaje()
        {
            this.adecuaciones_peritaje = new HashSet<adecuaciones_peritaje>();
            this.icb_insp_peritaje = new HashSet<icb_insp_peritaje>();
            this.icb_imagenes_peritaje = new HashSet<icb_imagenes_peritaje>();
            this.pperitajeoperacion = new HashSet<pperitajeoperacion>();
        }
    
        public int encab_insper_id { get; set; }
        public int encab_insper_idclasper { get; set; }
        public System.DateTime encab_insper_fecha { get; set; }
        public int encab_insper_idusuario { get; set; }
        public int encab_insper_idsolicitud { get; set; }
        public Nullable<int> encab_insper_clasificacion { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fec_aprobacion { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string motivo_rechazo { get; set; }
        public Nullable<int> user_aprobacion { get; set; }
        public string adecuaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adecuaciones_peritaje> adecuaciones_peritaje { get; set; }
        public virtual icb_clas_peritaje icb_clas_peritaje { get; set; }
        public virtual icb_clas_peritaje icb_clas_peritaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_insp_peritaje> icb_insp_peritaje { get; set; }
        public virtual icb_solicitud_peritaje icb_solicitud_peritaje { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_imagenes_peritaje> icb_imagenes_peritaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pperitajeoperacion> pperitajeoperacion { get; set; }
    }
}
