//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_plazo
    {
        public int plazo_id { get; set; }
        public Nullable<int> plazo_tiempo { get; set; }
        public Nullable<System.DateTime> plazo_fecela { get; set; }
        public Nullable<int> plazo_usuela { get; set; }
        public Nullable<int> plazo_licencia { get; set; }
        public Nullable<System.DateTime> plazo_fecha_actualizacion { get; set; }
        public Nullable<int> plazo_usuario_actualizacion { get; set; }
        public bool plazo_estado { get; set; }
        public Nullable<int> plazo_plan_id { get; set; }
    }
}
