//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_tinspeccionsistemasvh
    {
        public int tinsvh_id { get; set; }
        public Nullable<int> tsope_id { get; set; }
        public Nullable<int> ot_id { get; set; }
        public string tinsvh_estado { get; set; }
        public Nullable<bool> tinsvh_autorizar { get; set; }
        public Nullable<System.DateTime> tinsvh_fecenviosms { get; set; }
        public Nullable<bool> tinsvh_resp_sms { get; set; }
        public string tinsvh_observacion { get; set; }
    
        public virtual tencabezaorden tencabezaorden { get; set; }
        public virtual icb_tsistemas_operaciones icb_tsistemas_operaciones { get; set; }
    }
}
