//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_tpllamadarescate
    {
        public int tpllamada_id { get; set; }
        public string tpllamada_nombre { get; set; }
        public bool tpllamada_estado { get; set; }
        public System.DateTime tpllamada_fec_creacion { get; set; }
        public int tpllamada_usuela { get; set; }
        public Nullable<System.DateTime> tpllamada_fec_actualizacion { get; set; }
        public Nullable<int> tpllamada_usu_actualizacion { get; set; }
        public int tpllamada_licencia { get; set; }
        public string tpllamada_razon_inanctivo { get; set; }
    }
}
