//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_tptramite_prospecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_tptramite_prospecto()
        {
            this.icb_hist_prospecto = new HashSet<icb_hist_prospecto>();
            this.icb_terceros = new HashSet<icb_terceros>();
            this.prospectos = new HashSet<prospectos>();
            this.tipotramiteasesor = new HashSet<tipotramiteasesor>();
        }
    
        public int tptrapros_id { get; set; }
        public string tptrapros_descripcion { get; set; }
        public bool tptrapros_estado { get; set; }
        public Nullable<int> tptrapros_usucreacion { get; set; }
        public Nullable<System.DateTime> tptrapros_feccreacion { get; set; }
        public Nullable<System.DateTime> tptrapros_fecactualizacion { get; set; }
        public Nullable<int> tptrapros_usuactualizacion { get; set; }
        public Nullable<int> tptrapros_licencia { get; set; }
        public string tptrapros_razoninactivo { get; set; }
        public bool pide_asesor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_hist_prospecto> icb_hist_prospecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_terceros> icb_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospectos> prospectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipotramiteasesor> tipotramiteasesor { get; set; }
    }
}
