//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_medida_averia
    {
        public int medida_id { get; set; }
        public Nullable<int> medida_licencia { get; set; }
        public System.DateTime medida_fec_creacion { get; set; }
        public int medida_userid_creacion { get; set; }
        public Nullable<System.DateTime> medida_fec_actualizacion { get; set; }
        public Nullable<int> medida_userid_actualizacion { get; set; }
        public string medida_descripcion { get; set; }
        public bool medida_estado { get; set; }
        public string medida_razon_inactivo { get; set; }
    }
}
