//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_caja_detalle
    {
        public int id { get; set; }
        public Nullable<int> nombre { get; set; }
        public Nullable<int> caja { get; set; }
    
        public virtual icb_caja icb_caja { get; set; }
        public virtual icb_caja_nombre icb_caja_nombre { get; set; }
    }
}
