//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_tpperitaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_tpperitaje()
        {
            this.icb_solicitud_peritaje = new HashSet<icb_solicitud_peritaje>();
        }
    
        public int tpper_id { get; set; }
        public string tpper_nombre { get; set; }
        public bool tpper_estado { get; set; }
        public Nullable<int> tpper_licencia { get; set; }
        public Nullable<System.DateTime> tpperfec_creacion { get; set; }
        public Nullable<System.DateTime> tpperfec_actualizacion { get; set; }
        public Nullable<int> tpperouserid_creacion { get; set; }
        public Nullable<int> tpperuserid_actualizacion { get; set; }
        public string razoninactivo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_solicitud_peritaje> icb_solicitud_peritaje { get; set; }
    }
}
