//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_caja()
        {
            this.detalle_formas_pago_factura = new HashSet<detalle_formas_pago_factura>();
            this.detalle_formas_pago_orden = new HashSet<detalle_formas_pago_orden>();
            this.icb_caja_detalle = new HashSet<icb_caja_detalle>();
            this.icb_cuadre_caja = new HashSet<icb_cuadre_caja>();
            this.medios_caja = new HashSet<medios_caja>();
            this.transaciones_caja = new HashSet<transaciones_caja>();
            this.usuarios_caja = new HashSet<usuarios_caja>();
        }
    
        public int id { get; set; }
        public string grupo { get; set; }
        public Nullable<int> bodega { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> numero { get; set; }
    
        public virtual area_bodega area_bodega { get; set; }
        public virtual bodega_concesionario bodega_concesionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_formas_pago_factura> detalle_formas_pago_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_formas_pago_orden> detalle_formas_pago_orden { get; set; }
        public virtual icb_caja_estados icb_caja_estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_caja_detalle> icb_caja_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_cuadre_caja> icb_cuadre_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medios_caja> medios_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaciones_caja> transaciones_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_caja> usuarios_caja { get; set; }
    }
}
