//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_arch_tombat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_arch_tombat()
        {
            this.icb_arch_tombat_log = new HashSet<icb_arch_tombat_log>();
            this.icb_vehiculo_bateria = new HashSet<icb_vehiculo_bateria>();
        }
    
        public int arch_tombat_id { get; set; }
        public string arch_tombat_nombre { get; set; }
        public System.DateTime arch_tombat_fecha { get; set; }
        public int items { get; set; }
        public int toma_bateria_id { get; set; }
    
        public virtual icb_toma_baterias icb_toma_baterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_arch_tombat_log> icb_arch_tombat_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo_bateria> icb_vehiculo_bateria { get; set; }
    }
}
