//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_solicitud_peritaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_solicitud_peritaje()
        {
            this.icb_encabezado_insp_peritaje = new HashSet<icb_encabezado_insp_peritaje>();
        }
    
        public int id_peritaje { get; set; }
        public int id_tercero_vhretoma { get; set; }
        public System.DateTime fecha_agenda_peritaje { get; set; }
        public int tp_peritaje { get; set; }
        public Nullable<System.DateTime> fecha_inspeccion_peritaje { get; set; }
        public bool atendida { get; set; }
        public bool cancelada { get; set; }
        public bool reprogramada { get; set; }
        public Nullable<System.DateTime> fec_cita_anterior { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_encabezado_insp_peritaje> icb_encabezado_insp_peritaje { get; set; }
        public virtual icb_tpperitaje icb_tpperitaje { get; set; }
        public virtual icb_tercero_vhretoma icb_tercero_vhretoma { get; set; }
    }
}
