//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_zona_averia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_zona_averia()
        {
            this.icb_inspeccionvehiculos = new HashSet<icb_inspeccionvehiculos>();
        }
    
        public int zona_id { get; set; }
        public Nullable<int> zona_licencia { get; set; }
        public System.DateTime zona_fec_creacion { get; set; }
        public int zona_userid_creacion { get; set; }
        public Nullable<System.DateTime> zona_fec_actualizacion { get; set; }
        public Nullable<int> zona_userid_actualizacion { get; set; }
        public string zona_descripcion { get; set; }
        public bool zona_estado { get; set; }
        public string zona_razon_inactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_inspeccionvehiculos> icb_inspeccionvehiculos { get; set; }
    }
}
