//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_plan_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_plan_pago()
        {
            this.icb_plan_matriz = new HashSet<icb_plan_matriz>();
        }
    
        public int id { get; set; }
        public Nullable<int> asesor_id { get; set; }
        public Nullable<int> licencia_id { get; set; }
        public Nullable<int> cotizacion_id { get; set; }
        public string tasa_interes { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<decimal> credito { get; set; }
        public Nullable<decimal> cuota_inicial { get; set; }
        public string cuotas { get; set; }
        public Nullable<int> plan_id { get; set; }
        public bool plan_elegido { get; set; }
        public string modelo { get; set; }
        public decimal valor_residual { get; set; }
        public decimal otros_valores { get; set; }
    
        public virtual icb_cotizacion icb_cotizacion { get; set; }
        public virtual icb_plan_financiero icb_plan_financiero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_plan_matriz> icb_plan_matriz { get; set; }
        public virtual modelo_vehiculo modelo_vehiculo { get; set; }
        public virtual users users { get; set; }
    }
}
