//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_tpbodega_mov
    {
        public int tpbod_id { get; set; }
        public string tpbod__descripcion { get; set; }
        public Nullable<System.DateTime> tpbod_fecha_creacion { get; set; }
        public Nullable<int> tpbod_usuario_creacion { get; set; }
        public Nullable<System.DateTime> tpbod_fecha_actualizacion { get; set; }
        public Nullable<int> tpbod_usuario_actualizacion { get; set; }
        public bool tpbod_estado { get; set; }
        public string tpbod_razon_inactivo { get; set; }
    }
}
