//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_tabla_migracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_tabla_migracion()
        {
            this.icb_columnas_tabla = new HashSet<icb_columnas_tabla>();
        }
    
        public int id { get; set; }
        public int id_migracion { get; set; }
        public long oid { get; set; }
        public string nombre_tabla { get; set; }
        public string tipo_elemento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_columnas_tabla> icb_columnas_tabla { get; set; }
        public virtual icb_migracion icb_migracion { get; set; }
    }
}
