//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_imagenes_peritaje
    {
        public int id { get; set; }
        public int idperitaje { get; set; }
        public string imagen { get; set; }
    
        public virtual icb_encabezado_insp_peritaje icb_encabezado_insp_peritaje { get; set; }
    }
}
