//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class icb_plan_financiero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icb_plan_financiero()
        {
            this.icb_detalle_plan = new HashSet<icb_detalle_plan>();
            this.icb_plan_pago = new HashSet<icb_plan_pago>();
            this.planfinancierobodega = new HashSet<planfinancierobodega>();
        }
    
        public int plan_id { get; set; }
        public Nullable<int> plan_licencia { get; set; }
        public Nullable<System.DateTime> plan_fecela { get; set; }
        public Nullable<int> plan_usuela { get; set; }
        public string plan_descripcion { get; set; }
        public bool plan_estado { get; set; }
        public string plan_nombre { get; set; }
        public string plan_imagen { get; set; }
        public bool plan_comision { get; set; }
        public Nullable<double> plan_porcentaje_comision { get; set; }
        public Nullable<int> plan_usuario_actualizacion { get; set; }
        public Nullable<System.DateTime> plan_fecha_actualizacion { get; set; }
        public string plan_razon_inactivo { get; set; }
        public int idfinanciera { get; set; }
        public Nullable<double> tasa_interes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_detalle_plan> icb_detalle_plan { get; set; }
        public virtual icb_unidad_financiera icb_unidad_financiera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_plan_pago> icb_plan_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planfinancierobodega> planfinancierobodega { get; set; }
    }
}
