//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicadores_generales
    {
        public int id { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<short> mes { get; set; }
        public Nullable<decimal> inventario_inicial { get; set; }
        public Nullable<decimal> compras_gm_ingresis { get; set; }
        public Nullable<decimal> compras_concesionarios { get; set; }
        public Nullable<decimal> compras_otros_repuestos { get; set; }
        public Nullable<decimal> compras_otros_accesorios { get; set; }
        public Nullable<decimal> total_compras { get; set; }
        public Nullable<decimal> total_ventas { get; set; }
        public Nullable<decimal> ajustes_inventario { get; set; }
        public Nullable<decimal> costo_venta { get; set; }
        public Nullable<decimal> inventario_final { get; set; }
        public Nullable<decimal> dif_inventario_enero { get; set; }
        public Nullable<decimal> inv_proceso { get; set; }
        public Nullable<decimal> inv_disponible { get; set; }
        public Nullable<decimal> inv_final { get; set; }
        public Nullable<decimal> variacion_inventario { get; set; }
        public Nullable<decimal> rotacion_inven { get; set; }
        public Nullable<decimal> lealtad_bruta { get; set; }
        public Nullable<decimal> lealtad_neta { get; set; }
        public Nullable<decimal> lealtad_neta_sin_acceso { get; set; }
        public Nullable<decimal> margen_bruto_sin_incent { get; set; }
        public Nullable<decimal> margen_bruto_con_incent { get; set; }
        public Nullable<decimal> fof { get; set; }
        public Nullable<decimal> obsolencia { get; set; }
    }
}
