//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class insumosplanmantenimiento
    {
        public long idplanma { get; set; }
        public int idplan { get; set; }
        public int modelogeneral { get; set; }
        public decimal porcentaje { get; set; }
    
        public virtual tplanmantenimiento tplanmantenimiento { get; set; }
        public virtual vmodelog vmodelog { get; set; }
    }
}
