//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineas_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lineas_documento()
        {
            this.lineas_documento1 = new HashSet<lineas_documento>();
            this.recibidotraslados = new HashSet<recibidotraslados>();
        }
    
        public int id { get; set; }
        public int id_encabezado { get; set; }
        public string codigo { get; set; }
        public int seq { get; set; }
        public System.DateTime fec { get; set; }
        public int nit { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<float> porcentaje_iva { get; set; }
        public decimal valor_unitario { get; set; }
        public Nullable<float> porcentaje_descuento { get; set; }
        public decimal costo_unitario { get; set; }
        public string adicional { get; set; }
        public Nullable<int> vendedor { get; set; }
        public int bodega { get; set; }
        public string und { get; set; }
        public decimal cantidad_und { get; set; }
        public decimal cantidad_pedida { get; set; }
        public decimal costo_unitario_sin { get; set; }
        public Nullable<int> pedido { get; set; }
        public float cantidad_otra_und { get; set; }
        public Nullable<int> telefono { get; set; }
        public string tipo_op { get; set; }
        public Nullable<int> numero_op { get; set; }
        public decimal cantidad_devuelta { get; set; }
        public string tipo_link { get; set; }
        public Nullable<int> numero_link { get; set; }
        public Nullable<int> seq_link { get; set; }
        public Nullable<short> cantidad_dos { get; set; }
        public string serial { get; set; }
        public Nullable<float> porc_dcto_2 { get; set; }
        public Nullable<float> porc_dcto_3 { get; set; }
        public Nullable<int> Id_Documentos_lin_ped { get; set; }
        public string desc_adicional { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<float> impoconsumo { get; set; }
        public decimal costo_niff { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public Nullable<int> id_tarifa_cliente { get; set; }
        public string codigo_reemplazo { get; set; }
        public Nullable<int> id_solicitud_repuesto { get; set; }
        public Nullable<int> centro_costo { get; set; }
        public Nullable<int> id_linea_relacionado { get; set; }
        public Nullable<int> id_precarga { get; set; }
        public bool mensajeria_atendido { get; set; }
        public Nullable<int> idestadoremision { get; set; }
        public Nullable<int> diasComprometidos { get; set; }
        public Nullable<bool> comprometido { get; set; }
    
        public virtual centro_costo centro_costo1 { get; set; }
        public virtual encab_documento encab_documento { get; set; }
        public virtual EstadosRemision EstadosRemision { get; set; }
        public virtual EstadosRemision EstadosRemision1 { get; set; }
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual icb_referencia icb_referencia1 { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual rtipocliente rtipocliente { get; set; }
        public virtual rtipocliente rtipocliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineas_documento> lineas_documento1 { get; set; }
        public virtual lineas_documento lineas_documento2 { get; set; }
        public virtual rprecarga rprecarga { get; set; }
        public virtual tsolicitudrepuestosot tsolicitudrepuestosot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibidotraslados> recibidotraslados { get; set; }
    }
}
