//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineas_documento_operaciones
    {
        public int id { get; set; }
        public int id_encabezado { get; set; }
        public string codigo_operacion { get; set; }
        public int seq { get; set; }
        public System.DateTime fec { get; set; }
        public int nit { get; set; }
        public float tiempo { get; set; }
        public Nullable<float> porcentaje_iva { get; set; }
        public decimal valor_unitario { get; set; }
        public Nullable<float> porcentaje_descuento { get; set; }
        public decimal costo_unitario { get; set; }
        public string adicional { get; set; }
        public Nullable<int> vendedor { get; set; }
        public int bodega { get; set; }
        public string und { get; set; }
        public decimal costo_unitario_sin { get; set; }
        public Nullable<int> pedido { get; set; }
        public Nullable<int> telefono { get; set; }
        public string tipo_op { get; set; }
        public Nullable<int> numero_op { get; set; }
        public string tipo_link { get; set; }
        public Nullable<int> numero_link { get; set; }
        public Nullable<int> seq_link { get; set; }
        public string serial { get; set; }
        public Nullable<float> porc_dcto_2 { get; set; }
        public Nullable<float> porc_dcto_3 { get; set; }
        public Nullable<int> Id_Documentos_lin_ped { get; set; }
        public string desc_adicional { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<float> impoconsumo { get; set; }
        public decimal costo_niff { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public Nullable<int> id_tarifa_cliente { get; set; }
        public Nullable<int> iddetallemanoobra { get; set; }
        public Nullable<int> centro_costo { get; set; }
        public Nullable<decimal> tecnico_pagar { get; set; }
    
        public virtual centro_costo centro_costo1 { get; set; }
        public virtual encab_documento encab_documento { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual rtipocliente rtipocliente { get; set; }
        public virtual ttempario ttempario { get; set; }
        public virtual tdetallemanoobraot tdetallemanoobraot { get; set; }
    }
}
