//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_impresion_documentos
    {
        public long idencabezadofactura { get; set; }
        public int idencabezado { get; set; }
        public bool impreso { get; set; }
        public Nullable<System.DateTime> fecha_impresion { get; set; }
    
        public virtual encab_documento encab_documento { get; set; }
    }
}
