//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_busqueda
    {
        public int menu_busqueda_id { get; set; }
        public int menu_busqueda_id_menu { get; set; }
        public string menu_busqueda_nombre { get; set; }
        public string menu_busqueda_campo { get; set; }
        public Nullable<int> menu_busqueda_id_pestana { get; set; }
        public string menu_busqueda_vista { get; set; }
        public string menu_busqueda_tipo_campo { get; set; }
        public string menu_busqueda_consulta { get; set; }
        public bool menu_busqueda_multiple { get; set; }
    }
}
