//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesactualbodega
    {
        public int id { get; set; }
        public int idbodega { get; set; }
        public int anoactual { get; set; }
        public int mesacual { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
    
        public virtual bodega_concesionario bodega_concesionario { get; set; }
        public virtual users users { get; set; }
    }
}
