//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nom_departamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nom_departamento()
        {
            this.bodega_concesionario = new HashSet<bodega_concesionario>();
            this.nom_ciudad = new HashSet<nom_ciudad>();
            this.users = new HashSet<users>();
            this.vpedido = new HashSet<vpedido>();
        }
    
        public int dpto_id { get; set; }
        public int pais_id { get; set; }
        public string cod_dpto { get; set; }
        public string dpto_nombre { get; set; }
        public bool dpto_estado { get; set; }
        public Nullable<System.DateTime> dptofec_creacion { get; set; }
        public Nullable<System.DateTime> dptofec_actualizacion { get; set; }
        public Nullable<int> dptoid_licencia { get; set; }
        public Nullable<int> dptouserid_creacion { get; set; }
        public Nullable<int> dptouserid_actualizacion { get; set; }
        public string dpto_razoninactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodega_concesionario> bodega_concesionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nom_ciudad> nom_ciudad { get; set; }
        public virtual nom_pais nom_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedido> vpedido { get; set; }
    }
}
