//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nom_pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nom_pais()
        {
            this.bodega_concesionario = new HashSet<bodega_concesionario>();
            this.icb_terceros = new HashSet<icb_terceros>();
            this.nom_departamento = new HashSet<nom_departamento>();
        }
    
        public int pais_id { get; set; }
        public string cod_pais { get; set; }
        public string pais_nombre { get; set; }
        public bool pais_estado { get; set; }
        public Nullable<int> paisid_licencia { get; set; }
        public Nullable<int> paisuserid_creacion { get; set; }
        public Nullable<int> paisuserid_actualizacion { get; set; }
        public string pais_razoninactivo { get; set; }
        public Nullable<System.DateTime> paisfec_actualizacion { get; set; }
        public Nullable<System.DateTime> paisfec_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodega_concesionario> bodega_concesionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_terceros> icb_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nom_departamento> nom_departamento { get; set; }
    }
}
