//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcion_acceso_rol
    {
        public long id_opcion_acceso_rol { get; set; }
        public int id_opcion_acceso { get; set; }
        public int id_rol { get; set; }
    
        public virtual opcion_acceso opcion_acceso { get; set; }
        public virtual rols rols { get; set; }
    }
}
