//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagoscomprobanteegreso
    {
        public int id { get; set; }
        public int idEncab { get; set; }
        public int formaPago { get; set; }
        public decimal valor { get; set; }
        public string cheque { get; set; }
        public int perfilContable { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int userid_creacion { get; set; }
    
        public virtual encab_documento encab_documento { get; set; }
        public virtual perfil_contable_documento perfil_contable_documento { get; set; }
        public virtual users users { get; set; }
    }
}
