//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametrizacion_horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parametrizacion_horario()
        {
            this.vhorarionovedad = new HashSet<vhorarionovedad>();
        }
    
        public int horario_id { get; set; }
        public string tipo_horario { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> demo_id { get; set; }
        public Nullable<int> user_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> user_actualizacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<System.TimeSpan> lunes_desde { get; set; }
        public Nullable<System.TimeSpan> lunes_hasta { get; set; }
        public Nullable<System.TimeSpan> lunes_desde2 { get; set; }
        public Nullable<System.TimeSpan> lunes_hasta2 { get; set; }
        public bool lunes_disponible { get; set; }
        public Nullable<System.TimeSpan> martes_desde { get; set; }
        public Nullable<System.TimeSpan> martes_hasta { get; set; }
        public Nullable<System.TimeSpan> martes_desde2 { get; set; }
        public Nullable<System.TimeSpan> martes_hasta2 { get; set; }
        public bool martes_disponible { get; set; }
        public Nullable<System.TimeSpan> miercoles_desde { get; set; }
        public Nullable<System.TimeSpan> miercoles_hasta { get; set; }
        public Nullable<System.TimeSpan> miercoles_desde2 { get; set; }
        public Nullable<System.TimeSpan> miercoles_hasta2 { get; set; }
        public bool miercoles_disponible { get; set; }
        public Nullable<System.TimeSpan> jueves_desde { get; set; }
        public Nullable<System.TimeSpan> jueves_hasta { get; set; }
        public Nullable<System.TimeSpan> jueves_desde2 { get; set; }
        public Nullable<System.TimeSpan> jueves_hasta2 { get; set; }
        public bool jueves_disponible { get; set; }
        public Nullable<System.TimeSpan> viernes_desde { get; set; }
        public Nullable<System.TimeSpan> viernes_hasta { get; set; }
        public Nullable<System.TimeSpan> viernes_desde2 { get; set; }
        public Nullable<System.TimeSpan> viernes_hasta2 { get; set; }
        public bool viernes_disponible { get; set; }
        public Nullable<System.TimeSpan> sabado_desde { get; set; }
        public Nullable<System.TimeSpan> sabado_hasta { get; set; }
        public Nullable<System.TimeSpan> sabado_desde2 { get; set; }
        public Nullable<System.TimeSpan> sabado_hasta2 { get; set; }
        public bool sabado_disponible { get; set; }
        public Nullable<System.TimeSpan> domingo_desde { get; set; }
        public Nullable<System.TimeSpan> domingo_hasta { get; set; }
        public Nullable<System.TimeSpan> domingo_desde2 { get; set; }
        public Nullable<System.TimeSpan> domingo_hasta2 { get; set; }
        public bool domingo_disponible { get; set; }
        public string observaciones { get; set; }
        public bool no_disponible { get; set; }
        public Nullable<System.DateTime> ndispo_fecha_inicio { get; set; }
        public Nullable<System.DateTime> ndispo_fecha_fin { get; set; }
    
        public virtual vdemos vdemos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vhorarionovedad> vhorarionovedad { get; set; }
    }
}
