//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_contable_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public perfil_contable_documento()
        {
            this.pagoscomprobanteegreso = new HashSet<pagoscomprobanteegreso>();
            this.perfil_contable_bodega = new HashSet<perfil_contable_bodega>();
            this.perfil_cuentas_documento = new HashSet<perfil_cuentas_documento>();
            this.vtipo_compra_vehiculos = new HashSet<vtipo_compra_vehiculos>();
        }
    
        public int id { get; set; }
        public int tipo { get; set; }
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public bool compraautomatica { get; set; }
        public string iva { get; set; }
        public Nullable<int> regimen_tercero { get; set; }
    
        public virtual contributario contributario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagoscomprobanteegreso> pagoscomprobanteegreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfil_contable_bodega> perfil_contable_bodega { get; set; }
        public virtual tpregimen_tercero tpregimen_tercero { get; set; }
        public virtual tp_doc_registros tp_doc_registros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfil_cuentas_documento> perfil_cuentas_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtipo_compra_vehiculos> vtipo_compra_vehiculos { get; set; }
    }
}
