//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfilcontable_referencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public perfilcontable_referencia()
        {
            this.icb_referencia = new HashSet<icb_referencia>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cuenta_ventas { get; set; }
        public Nullable<int> cuenta_iva { get; set; }
        public Nullable<int> cuenta_dev_ventas { get; set; }
        public Nullable<int> cuenta_dev_iva { get; set; }
        public Nullable<int> cuenta_inv_compra { get; set; }
        public Nullable<int> cuenta_iva_compras { get; set; }
        public Nullable<int> cuenta_dev_inv_compra { get; set; }
        public Nullable<int> cuenta_dev_iva_compras { get; set; }
        public Nullable<int> cta_inventario { get; set; }
        public Nullable<int> cuenta_costo { get; set; }
        public Nullable<int> centro { get; set; }
        public Nullable<int> cuenta_descuento { get; set; }
        public Nullable<int> cuenta_impoconsumo { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_referencia> icb_referencia { get; set; }
    }
}
