//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prospectos()
        {
            this.asignacion = new HashSet<asignacion>();
            this.segmentacion_historico_clientes_crm = new HashSet<segmentacion_historico_clientes_crm>();
            this.sesion_logasesor = new HashSet<sesion_logasesor>();
        }
    
        public int id { get; set; }
        public Nullable<int> tpdoc_id { get; set; }
        public string documento { get; set; }
        public string prinom_tercero { get; set; }
        public string segnom_tercero { get; set; }
        public string apellido_tercero { get; set; }
        public string segapellido_tercero { get; set; }
        public string razonsocial { get; set; }
        public string digitoverificacion { get; set; }
        public string email_tercero { get; set; }
        public string telf_tercero { get; set; }
        public string celular_tercero { get; set; }
        public Nullable<int> genero_tercero { get; set; }
        public int tptramite { get; set; }
        public Nullable<int> asesor_id { get; set; }
        public Nullable<int> origen_id { get; set; }
        public Nullable<int> subfuente { get; set; }
        public Nullable<int> medcomun_id { get; set; }
        public Nullable<int> sitioevento { get; set; }
        public string observaciones { get; set; }
        public bool habdtautor_correo { get; set; }
        public bool habdtautor_celular { get; set; }
        public bool habdtautor_msm { get; set; }
        public bool habdtautor_watsap { get; set; }
        public Nullable<int> numfamiliares { get; set; }
        public Nullable<int> numamigos { get; set; }
        public int bodega { get; set; }
        public int estado { get; set; }
        public Nullable<int> temperatura { get; set; }
        public Nullable<int> licencia { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<int> userid_creacion { get; set; }
        public Nullable<int> idtercero { get; set; }
        public string modelo { get; set; }
        public string modelo1 { get; set; }
        public bool visita { get; set; }
        public Nullable<int> buscarAsesor_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion> asignacion { get; set; }
        public virtual bodega_concesionario bodega_concesionario { get; set; }
        public virtual gen_tercero gen_tercero { get; set; }
        public virtual icb_medio_comunicacion icb_medio_comunicacion { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual icb_tptramite_prospecto icb_tptramite_prospecto { get; set; }
        public virtual modelo_vehiculo modelo_vehiculo { get; set; }
        public virtual modelo_vehiculo modelo_vehiculo1 { get; set; }
        public virtual tp_documento tp_documento { get; set; }
        public virtual tp_origen tp_origen { get; set; }
        public virtual tp_subfuente tp_subfuente { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual veventosorigen veventosorigen { get; set; }
        public virtual vtemperatura vtemperatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segmentacion_historico_clientes_crm> segmentacion_historico_clientes_crm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sesion_logasesor> sesion_logasesor { get; set; }
    }
}
