//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdetallesolicitud
    {
        public int id { get; set; }
        public int id_solicitud { get; set; }
        public string referencia { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> iva { get; set; }
        public Nullable<decimal> valor { get; set; }
        public int userid_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> userid_actualizacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> IDRSEPARACION { get; set; }
        public int esta_pedido { get; set; }
        public string nota_pedido { get; set; }
        public string archivo_pedido { get; set; }
        public string npedido_gm { get; set; }
        public Nullable<int> cantidad_recibida { get; set; }
        public Nullable<int> consecutivo_interno { get; set; }
    
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual restados_detallesolicitud_repuestos restados_detallesolicitud_repuestos { get; set; }
        public virtual rsolicitudesrepuestos rsolicitudesrepuestos { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
