//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencias_comprometidas
    {
        public int id { get; set; }
        public Nullable<int> doc_cliente { get; set; }
        public Nullable<System.DateTime> fecha_comprometido { get; set; }
        public Nullable<System.DateTime> fecha_descomprometido { get; set; }
        public Nullable<int> tiempo_incumplido { get; set; }
        public Nullable<int> estados { get; set; }
        public Nullable<int> numero_pedido { get; set; }
        public Nullable<int> numero_OT { get; set; }
        public Nullable<int> numero_separacion { get; set; }
        public Nullable<int> numero_anticipo { get; set; }
        public Nullable<int> numero_solicitud_traslado { get; set; }
        public Nullable<int> numero_recepcion_traslado { get; set; }
        public Nullable<int> numero_despacho_taller { get; set; }
        public Nullable<int> numero_despacho_bodega { get; set; }
        public Nullable<int> numero_remision { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string codigo { get; set; }
    
        public virtual encab_documento encab_documento { get; set; }
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual icb_referencia_mov icb_referencia_mov { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual recibidotraslados recibidotraslados { get; set; }
        public virtual recibidotraslados recibidotraslados1 { get; set; }
        public virtual rseparacionmercancia rseparacionmercancia { get; set; }
        public virtual Solicitud_traslado Solicitud_traslado { get; set; }
        public virtual tencabezaorden tencabezaorden { get; set; }
    }
}
