//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenciaskits
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public decimal precio { get; set; }
        public int idkitaccesorios { get; set; }
        public int cantidad { get; set; }
    
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual kitsaccesorios kitsaccesorios { get; set; }
    }
}
