//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolacceso
    {
        public int id { get; set; }
        public int idrol { get; set; }
        public int idpermiso { get; set; }
    
        public virtual rolpermisos rolpermisos { get; set; }
        public virtual rols rols { get; set; }
    }
}
