//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class segmento_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public segmento_vehiculo()
        {
            this.modelo_vehiculo = new HashSet<modelo_vehiculo>();
        }
    
        public int segvh_id { get; set; }
        public Nullable<int> segvhid_licencia { get; set; }
        public System.DateTime segvhfec_creacion { get; set; }
        public int segvhuserid_creacion { get; set; }
        public Nullable<System.DateTime> segvhfec_actualizacion { get; set; }
        public Nullable<int> segvhuserid_actualizacion { get; set; }
        public string segvh_nombre { get; set; }
        public bool segvh_estado { get; set; }
        public string segvhrazoninactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelo_vehiculo> modelo_vehiculo { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
