//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguicarteratercero
    {
        public int seg_id { get; set; }
        public int tercero_id { get; set; }
        public int tipo_id { get; set; }
        public string nota { get; set; }
        public System.DateTime fecha { get; set; }
        public int user_creacion_id { get; set; }
        public int encabezado_id { get; set; }
    
        public virtual encab_documento encab_documento { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual vtiposeguimientocot vtiposeguimientocot { get; set; }
    }
}
