//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablaempresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tablaempresa()
        {
            this.activosfijos = new HashSet<activosfijos>();
            this.amortizacionfijos = new HashSet<amortizacionfijos>();
        }
    
        public int id { get; set; }
        public string nombre_empresa { get; set; }
        public string nit { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public int cuenta_utilidad { get; set; }
        public int cuenta_inicial { get; set; }
        public int cuenta_final { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public string codigoconcesionario { get; set; }
        public Nullable<int> digitoverificacion { get; set; }
        public string celular { get; set; }
        public int anoactual { get; set; }
        public int mesactual { get; set; }
        public int perfiltributario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfijos> activosfijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfijos> amortizacionfijos { get; set; }
        public virtual cuenta_puc cuenta_puc { get; set; }
        public virtual cuenta_puc cuenta_puc1 { get; set; }
        public virtual cuenta_puc cuenta_puc2 { get; set; }
        public virtual tpregimen_tercero tpregimen_tercero { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
