//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbahias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbahias()
        {
            this.bahia_alistamiento_exh = new HashSet<bahia_alistamiento_exh>();
            this.bahia_alistamiento_exh1 = new HashSet<bahia_alistamiento_exh>();
            this.icb_bahia_alistamiento = new HashSet<icb_bahia_alistamiento>();
            this.tcambiobahiatecnico = new HashSet<tcambiobahiatecnico>();
            this.tcitastaller = new HashSet<tcitastaller>();
            this.tencabinspeccion = new HashSet<tencabinspeccion>();
            this.tcambiobahiatecnico1 = new HashSet<tcambiobahiatecnico>();
        }
    
        public int id { get; set; }
        public int bodega { get; set; }
        public int tipo_bahia { get; set; }
        public string codigo_bahia { get; set; }
        public int tipo_tecnico { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<int> idtecnico { get; set; }
        public Nullable<bool> bahiavirtual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahia_alistamiento_exh> bahia_alistamiento_exh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahia_alistamiento_exh> bahia_alistamiento_exh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_bahia_alistamiento> icb_bahia_alistamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcambiobahiatecnico> tcambiobahiatecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitastaller> tcitastaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabinspeccion> tencabinspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcambiobahiatecnico> tcambiobahiatecnico1 { get; set; }
    }
}
