//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcotdetallemanoobra
    {
        public int id { get; set; }
        public int idencab { get; set; }
        public string operacion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<float> tiempo { get; set; }
        public Nullable<decimal> porceniva { get; set; }
        public Nullable<decimal> porcendescto { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> valortotal { get; set; }
        public Nullable<decimal> tarifamanoobra { get; set; }
    
        public virtual tencabcotizacion tencabcotizacion { get; set; }
    }
}
