//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcotdetallerepuesto
    {
        public int id { get; set; }
        public int idencab { get; set; }
        public string ref_codigo { get; set; }
        public float cantidad { get; set; }
        public decimal valorunitario { get; set; }
        public Nullable<float> porcen_iva { get; set; }
        public Nullable<float> porcen_dscto { get; set; }
        public decimal costo_promedio { get; set; }
        public Nullable<int> idcotrepuesto { get; set; }
    
        public virtual icb_cotizacion icb_cotizacion { get; set; }
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual tencabcotizacion tencabcotizacion { get; set; }
    }
}
