//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdetallemanoobraot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tdetallemanoobraot()
        {
            this.lineas_documento_operaciones = new HashSet<lineas_documento_operaciones>();
            this.tpausasorden = new HashSet<tpausasorden>();
        }
    
        public int id { get; set; }
        public int idorden { get; set; }
        public string idtempario { get; set; }
        public int idtecnico { get; set; }
        public Nullable<decimal> tiempo { get; set; }
        public decimal valorunitario { get; set; }
        public Nullable<int> tipotarifa { get; set; }
        public string estado { get; set; }
        public Nullable<int> nitoperacion { get; set; }
        public Nullable<decimal> pordescuento { get; set; }
        public Nullable<decimal> costopromedio { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public Nullable<decimal> poriva { get; set; }
        public Nullable<System.DateTime> fecreinicio { get; set; }
        public Nullable<int> tipodoc { get; set; }
        public Nullable<int> numerodoc { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> idcentro { get; set; }
        public Nullable<int> id_plan_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_envio_sms { get; set; }
        public Nullable<bool> respuesta_sms { get; set; }
        public string observacion_sms { get; set; }
        public Nullable<bool> respuestainterno { get; set; }
        public string observacioninterva { get; set; }
    
        public virtual centro_costo centro_costo { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineas_documento_operaciones> lineas_documento_operaciones { get; set; }
        public virtual rtipocliente rtipocliente { get; set; }
        public virtual tencabezaorden tencabezaorden { get; set; }
        public virtual tp_doc_registros tp_doc_registros { get; set; }
        public virtual tplanmantenimiento tplanmantenimiento { get; set; }
        public virtual ttecnicos ttecnicos { get; set; }
        public virtual ttempario ttempario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpausasorden> tpausasorden { get; set; }
    }
}
