//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempSolicitud
    {
        public int idtemp { get; set; }
        public Nullable<int> dataBogeda { get; set; }
        public Nullable<int> dataCliente { get; set; }
        public Nullable<int> idkitaccesorios { get; set; }
        public Nullable<int> dataBogeda2 { get; set; }
        public string idreferencia { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> idseparacion { get; set; }
    
        public virtual bodega_concesionario bodega_concesionario { get; set; }
        public virtual bodega_concesionario bodega_concesionario1 { get; set; }
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual kitsaccesorios kitsaccesorios { get; set; }
    }
}
