//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tencabinspeccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tencabinspeccion()
        {
            this.crm_campinspecciontaller = new HashSet<crm_campinspecciontaller>();
            this.tdetalleinspeccion = new HashSet<tdetalleinspeccion>();
            this.tinspeccionmensaje = new HashSet<tinspeccionmensaje>();
            this.ttareainspeccionprioridad = new HashSet<ttareainspeccionprioridad>();
        }
    
        public int id { get; set; }
        public string vehiculo { get; set; }
        public Nullable<int> idtecnico { get; set; }
        public Nullable<int> idbahia { get; set; }
        public Nullable<int> idcita { get; set; }
        public int idtercero { get; set; }
        public long kilometraje { get; set; }
        public int idcombustible { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_campinspecciontaller> crm_campinspecciontaller { get; set; }
        public virtual icb_terceros icb_terceros { get; set; }
        public virtual icb_vehiculo icb_vehiculo { get; set; }
        public virtual tbahias tbahias { get; set; }
        public virtual tcantcombustible tcantcombustible { get; set; }
        public virtual tcitastaller tcitastaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tdetalleinspeccion> tdetalleinspeccion { get; set; }
        public virtual ttecnicos ttecnicos { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tinspeccionmensaje> tinspeccionmensaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttareainspeccionprioridad> ttareainspeccionprioridad { get; set; }
    }
}
