//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tencabezaorden_exh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tencabezaorden_exh()
        {
            this.bahia_alistamiento_exh = new HashSet<bahia_alistamiento_exh>();
        }
    
        public int id { get; set; }
        public int idtipodoc { get; set; }
        public string codigoentrada { get; set; }
        public int bodega { get; set; }
        public int numero { get; set; }
        public string planmayor { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime entrega { get; set; }
        public string notas { get; set; }
        public long kilometraje { get; set; }
        public int razoningreso { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<int> tipooperacion { get; set; }
        public Nullable<int> idcita { get; set; }
        public Nullable<int> idtecnico { get; set; }
        public Nullable<int> estadoorden { get; set; }
        public Nullable<System.DateTime> fecha_inspeccion { get; set; }
        public Nullable<System.DateTime> fecha_solicitud_repuestos { get; set; }
        public Nullable<System.DateTime> fecha_inicio_operacion { get; set; }
        public Nullable<System.DateTime> fecha_fin_operacion { get; set; }
        public Nullable<int> centrocosto { get; set; }
        public Nullable<int> id_plan_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_inicio_inspeccion { get; set; }
        public Nullable<System.DateTime> fecha_impresion_cotizacion { get; set; }
        public Nullable<System.DateTime> fecha_liquidacion { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahia_alistamiento_exh> bahia_alistamiento_exh { get; set; }
        public virtual bodega_concesionario bodega_concesionario { get; set; }
        public virtual centro_costo centro_costo { get; set; }
        public virtual icb_vehiculo icb_vehiculo { get; set; }
        public virtual tcitasestados tcitasestados { get; set; }
        public virtual tcitastaller tcitastaller { get; set; }
        public virtual tp_doc_registros tp_doc_registros { get; set; }
        public virtual trazonesingreso trazonesingreso { get; set; }
        public virtual ttipooperacion ttipooperacion { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
