//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tercero_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tercero_proveedor()
        {
            this.activosfijos = new HashSet<activosfijos>();
            this.amortizacionfijos = new HashSet<amortizacionfijos>();
            this.tcotdetalletot = new HashSet<tcotdetalletot>();
            this.tordentot = new HashSet<tordentot>();
        }
    
        public int prtercero_id { get; set; }
        public Nullable<int> tercproid_licencia { get; set; }
        public Nullable<System.DateTime> tercprofec_creacion { get; set; }
        public Nullable<int> tercprouserid_creacion { get; set; }
        public Nullable<System.DateTime> tercprofec_actualizacion { get; set; }
        public Nullable<int> tercprouserid_actualizacion { get; set; }
        public string pgweb_tercero { get; set; }
        public string repreleg_tercero { get; set; }
        public bool rete_tercero { get; set; }
        public bool contrib_tercero { get; set; }
        public bool entidad_tercero { get; set; }
        public bool tercpro_estado { get; set; }
        public bool aplica_tercero { get; set; }
        public Nullable<float> tarifaica_tercero { get; set; }
        public int tercero_id { get; set; }
        public int acteco_id { get; set; }
        public Nullable<int> tpsuministro_id { get; set; }
        public int tpregimen_id { get; set; }
        public Nullable<int> tpimpu_id { get; set; }
        public string razoninactivo { get; set; }
        public Nullable<int> tipo_proveedor { get; set; }
        public int fpago_id { get; set; }
        public bool exentoiva { get; set; }
        public string telefono { get; set; }
        public string retica { get; set; }
        public string retfuente { get; set; }
        public string retiva { get; set; }
        public string autorretencion { get; set; }
    
        public virtual acteco_tercero acteco_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfijos> activosfijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfijos> amortizacionfijos { get; set; }
        public virtual contributario contributario { get; set; }
        public virtual contributario contributario1 { get; set; }
        public virtual contributario contributario2 { get; set; }
        public virtual contributario contributario3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcotdetalletot> tcotdetalletot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tordentot> tordentot { get; set; }
        public virtual tiposumi_tercero tiposumi_tercero { get; set; }
        public virtual tpimpu_tercero tpimpu_tercero { get; set; }
    }
}
