//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEstadosOT2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEstadosOT2()
        {
            this.tencabezaorden = new HashSet<tencabezaorden>();
            this.tEstadosOT21 = new HashSet<tEstadosOT2>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecha_creaciomn { get; set; }
        public Nullable<int> user_creacion { get; set; }
        public string razoninactivo { get; set; }
        public Nullable<int> Estadodepende { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabezaorden> tencabezaorden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEstadosOT2> tEstadosOT21 { get; set; }
        public virtual tEstadosOT2 tEstadosOT22 { get; set; }
        public virtual users users { get; set; }
    }
}
