//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocontratocomercial
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tpcontrato_id_licencia { get; set; }
        public System.DateTime tpcontrato_fec_creacion { get; set; }
        public int tpcontrato_userid_creacion { get; set; }
        public Nullable<System.DateTime> tpcontrato_fec_actualizacion { get; set; }
        public Nullable<int> tpcontrato_userid_actualizacion { get; set; }
        public bool tpcontrato__estado { get; set; }
        public string tpcontrato_razoninactivo { get; set; }
    }
}
