//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoproveedor
    {
        public int tipo { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public bool estado { get; set; }
        public string razoninactivo { get; set; }
        public Nullable<int> usuario_actualizacion { get; set; }
        public Nullable<int> licencia_id { get; set; }
        public Nullable<int> Clasificacion_pro { get; set; }
    
        public virtual Clasificacion_tipoProveedor Clasificacion_tipoProveedor { get; set; }
    }
}
