//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipotramiteasesor
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_tipotramite { get; set; }
    
        public virtual icb_tptramite_prospecto icb_tptramite_prospecto { get; set; }
        public virtual users users { get; set; }
    }
}
