//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_documento()
        {
            this.icb_contacto_tercero = new HashSet<icb_contacto_tercero>();
            this.prospectos = new HashSet<prospectos>();
            this.users = new HashSet<users>();
        }
    
        public int tpdoc_id { get; set; }
        public string tipo { get; set; }
        public string tpdoc_nombre { get; set; }
        public bool tpdoc_estado { get; set; }
        public Nullable<System.DateTime> tpdocfec_creacion { get; set; }
        public Nullable<System.DateTime> tpdocfec_actualizacion { get; set; }
        public Nullable<int> tpdocuserid_creacion { get; set; }
        public Nullable<int> tpdocuserid_actualizacion { get; set; }
        public Nullable<int> tpdocid_licencia { get; set; }
        public string tpdoc_razoninactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_contacto_tercero> icb_contacto_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospectos> prospectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users { get; set; }
        public virtual users users1 { get; set; }
        public virtual users users2 { get; set; }
    }
}
