//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpausasorden
    {
        public long id { get; set; }
        public int idorden { get; set; }
        public Nullable<int> operacion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> razon_pausa { get; set; }
        public string observacion_pausa { get; set; }
    
        public virtual tdetallemanoobraot tdetallemanoobraot { get; set; }
        public virtual tencabezaorden tencabezaorden { get; set; }
        public virtual tmotivospausa tmotivospausa { get; set; }
    }
}
