//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpmotor_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tpmotor_vehiculo()
        {
            this.modelo_vehiculo = new HashSet<modelo_vehiculo>();
        }
    
        public int tpmot_id { get; set; }
        public Nullable<int> tpmotid_licencia { get; set; }
        public System.DateTime tpmotorfec_creacion { get; set; }
        public int tpmotuser_id_creacion { get; set; }
        public Nullable<System.DateTime> tpmotfec_actualizacion { get; set; }
        public Nullable<int> tpmotuserid_actualizacion { get; set; }
        public string tpmot_nombre { get; set; }
        public bool tpmot_estado { get; set; }
        public string tpmotrazoninactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelo_vehiculo> modelo_vehiculo { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
