//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpservicio_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tpservicio_vehiculo()
        {
            this.icb_vehiculo = new HashSet<icb_vehiculo>();
        }
    
        public int tpserv_id { get; set; }
        public Nullable<int> tpservid_licencia { get; set; }
        public System.DateTime tpservfec_creacion { get; set; }
        public int tpservuserid_creacion { get; set; }
        public Nullable<System.DateTime> tpservfec_actualizacion { get; set; }
        public Nullable<int> tpservuserid_actualizacion { get; set; }
        public string tpserv_nombre { get; set; }
        public bool tpserv_estado { get; set; }
        public string tpservrazoninactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo> icb_vehiculo { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
