//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tptramitador_vh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tptramitador_vh()
        {
            this.tramitador_vh = new HashSet<tramitador_vh>();
        }
    
        public int tptramivh_id { get; set; }
        public Nullable<int> tptramivhid_licencia { get; set; }
        public System.DateTime tptramivhfec_creacion { get; set; }
        public int tptramivhuserid_creacion { get; set; }
        public Nullable<System.DateTime> tptramivhfec_actualizacion { get; set; }
        public Nullable<int> tptramivhuserid_actualizacion { get; set; }
        public string tptramivh_nombre { get; set; }
        public bool tptramivh_estado { get; set; }
        public string tptramivhrazoninactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tramitador_vh> tramitador_vh { get; set; }
    }
}
