//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tramitador_vh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tramitador_vh()
        {
            this.icb_vehiculo_eventos = new HashSet<icb_vehiculo_eventos>();
        }
    
        public int tramitador_id { get; set; }
        public Nullable<int> tramitadorid_licencia { get; set; }
        public System.DateTime tramitadorfec_creacion { get; set; }
        public int tramitadoruserid_creacion { get; set; }
        public Nullable<System.DateTime> tramitadorfec_actualizacion { get; set; }
        public Nullable<int> tramitadoruserid_actualizacion { get; set; }
        public string tramitador_documento { get; set; }
        public string tramitadorpri_nombre { get; set; }
        public string tramitadorseg_nombre { get; set; }
        public string tramitador_apellidos { get; set; }
        public string tramitador_celular { get; set; }
        public int tramitador_idtipo { get; set; }
        public bool tramitador_estado { get; set; }
        public string tramitador_razoninactivo { get; set; }
        public string tramitador_apellido2 { get; set; }
        public int tramitador_idtercero { get; set; }
    
        public virtual icb_terceros icb_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo_eventos> icb_vehiculo_eventos { get; set; }
        public virtual tptramitador_vh tptramitador_vh { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
