//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class trepuestossolicitados
    {
        public int id { get; set; }
        public int idorden { get; set; }
        public string idrepuesto { get; set; }
        public int cantidad { get; set; }
        public int solicitado { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecsolicitud { get; set; }
        public Nullable<int> familia { get; set; }
        public Nullable<int> linea { get; set; }
        public Nullable<int> grupo { get; set; }
        public Nullable<int> subgrupo { get; set; }
    
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual tencabezaorden tencabezaorden { get; set; }
    }
}
