//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsolicitudorden
    {
        public int idsolicitud { get; set; }
        public int idorden { get; set; }
        public int bodega { get; set; }
        public string solicitud { get; set; }
        public string respuesta { get; set; }
        public System.DateTime fecsolicitud { get; set; }
        public Nullable<System.DateTime> fecrespuesta { get; set; }
        public Nullable<int> usuariorespuesta { get; set; }
        public int usuariosolicitud { get; set; }
    
        public virtual tencabezaorden tencabezaorden { get; set; }
    }
}
