//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsolicitudrepuestosot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsolicitudrepuestosot()
        {
            this.lineas_documento = new HashSet<lineas_documento>();
        }
    
        public int id { get; set; }
        public int idorden { get; set; }
        public string idrepuesto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> valor { get; set; }
        public bool solicitado { get; set; }
        public Nullable<System.DateTime> fecsolicitud { get; set; }
        public Nullable<System.DateTime> fecrecibidor { get; set; }
        public bool recibido { get; set; }
        public Nullable<int> iddetalle { get; set; }
        public int canttraslado { get; set; }
        public bool pedido { get; set; }
        public string reemplazo { get; set; }
        public Nullable<int> estado_solicitud { get; set; }
        public Nullable<int> diasComprometidos { get; set; }
        public Nullable<bool> comprometido { get; set; }
    
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual icb_referencia icb_referencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineas_documento> lineas_documento { get; set; }
        public virtual tdetallerepuestosot tdetallerepuestosot { get; set; }
        public virtual tencabezaorden tencabezaorden { get; set; }
        public virtual testado_solicitud_repuesto testado_solicitud_repuesto { get; set; }
    }
}
