//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsuministromanoot
    {
        public long id_suministromanoot { get; set; }
        public string operacion { get; set; }
        public int modelo_general { get; set; }
        public string referencia { get; set; }
        public int cantidad { get; set; }
    
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual ttempario ttempario { get; set; }
        public virtual vmodelog vmodelog { get; set; }
    }
}
