//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicaciones_asignadas
    {
        public int id { get; set; }
        public Nullable<int> id_pareja { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public Nullable<int> id_encab { get; set; }
    
        public virtual aencab_auditoriainv aencab_auditoriainv { get; set; }
        public virtual apareja_auditoriainv apareja_auditoriainv { get; set; }
        public virtual ubicacion_repuestobod ubicacion_repuestobod { get; set; }
    }
}
