//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.acteco_tercero = new HashSet<acteco_tercero>();
            this.acteco_tercero1 = new HashSet<acteco_tercero>();
            this.activoclasificacion = new HashSet<activoclasificacion>();
            this.activoclasificacion1 = new HashSet<activoclasificacion>();
            this.activometodo = new HashSet<activometodo>();
            this.activometodo1 = new HashSet<activometodo>();
            this.activosfijos = new HashSet<activosfijos>();
            this.activosfijos1 = new HashSet<activosfijos>();
            this.activosfijos2 = new HashSet<activosfijos>();
            this.activosfubicacion = new HashSet<activosfubicacion>();
            this.activosfubicacion1 = new HashSet<activosfubicacion>();
            this.adecuaciones_peritaje = new HashSet<adecuaciones_peritaje>();
            this.aencab_auditoriainv = new HashSet<aencab_auditoriainv>();
            this.aencab_auditoriainv1 = new HashSet<aencab_auditoriainv>();
            this.agenda_asesor = new HashSet<agenda_asesor>();
            this.agenda_asesor1 = new HashSet<agenda_asesor>();
            this.agenda_demos = new HashSet<agenda_demos>();
            this.agenda_mensajero = new HashSet<agenda_mensajero>();
            this.agenda_mensajero1 = new HashSet<agenda_mensajero>();
            this.alertaasesor = new HashSet<alertaasesor>();
            this.alertaasesor1 = new HashSet<alertaasesor>();
            this.amodificaciones_auditoriainv = new HashSet<amodificaciones_auditoriainv>();
            this.amodificaciones_extra_auditoriainv = new HashSet<amodificaciones_extra_auditoriainv>();
            this.amortizacionclasificacion = new HashSet<amortizacionclasificacion>();
            this.amortizacionclasificacion1 = new HashSet<amortizacionclasificacion>();
            this.amortizacionfijos = new HashSet<amortizacionfijos>();
            this.amortizacionfijos1 = new HashSet<amortizacionfijos>();
            this.amortizacionfijos2 = new HashSet<amortizacionfijos>();
            this.amortizacionfubicacion = new HashSet<amortizacionfubicacion>();
            this.amortizacionfubicacion1 = new HashSet<amortizacionfubicacion>();
            this.apareja_auditoriainv = new HashSet<apareja_auditoriainv>();
            this.apareja_auditoriainv1 = new HashSet<apareja_auditoriainv>();
            this.archListaPrecios = new HashSet<archListaPrecios>();
            this.asesor_log = new HashSet<asesor_log>();
            this.asesor_log1 = new HashSet<asesor_log>();
            this.asignacion = new HashSet<asignacion>();
            this.autorizaciones = new HashSet<autorizaciones>();
            this.autorizaciones1 = new HashSet<autorizaciones>();
            this.bahia_alistamiento_exh = new HashSet<bahia_alistamiento_exh>();
            this.bahia_alistamiento_exh1 = new HashSet<bahia_alistamiento_exh>();
            this.bitacoraExcepcionFactura = new HashSet<bitacoraExcepcionFactura>();
            this.bitacoraExcepcionFactura1 = new HashSet<bitacoraExcepcionFactura>();
            this.bodega_concesionario = new HashSet<bodega_concesionario>();
            this.bodega_concesionario1 = new HashSet<bodega_concesionario>();
            this.bodega_usuario_visualizacion = new HashSet<bodega_usuario_visualizacion>();
            this.caja_menor = new HashSet<caja_menor>();
            this.caja_menor1 = new HashSet<caja_menor>();
            this.caja_menor_bodega = new HashSet<caja_menor_bodega>();
            this.caja_menor_bodega1 = new HashSet<caja_menor_bodega>();
            this.cambioubicacionveh = new HashSet<cambioubicacionveh>();
            this.cargacirculares = new HashSet<cargacirculares>();
            this.centro_costo = new HashSet<centro_costo>();
            this.clasificacion_cliente = new HashSet<clasificacion_cliente>();
            this.clasificacion_cliente1 = new HashSet<clasificacion_cliente>();
            this.clasificacion_repuesto = new HashSet<clasificacion_repuesto>();
            this.clasificacion_repuesto1 = new HashSet<clasificacion_repuesto>();
            this.clasificacion_vehiculo = new HashSet<clasificacion_vehiculo>();
            this.clasificacion_vehiculo1 = new HashSet<clasificacion_vehiculo>();
            this.color_vehiculo = new HashSet<color_vehiculo>();
            this.color_vehiculo1 = new HashSet<color_vehiculo>();
            this.crm_campinspecciontaller = new HashSet<crm_campinspecciontaller>();
            this.crm_campinspecciontaller1 = new HashSet<crm_campinspecciontaller>();
            this.crm_campvintaller = new HashSet<crm_campvintaller>();
            this.crm_encuesta_respuestas = new HashSet<crm_encuesta_respuestas>();
            this.crm_encuestas = new HashSet<crm_encuestas>();
            this.crm_encuestas1 = new HashSet<crm_encuestas>();
            this.cruce_documentos = new HashSet<cruce_documentos>();
            this.cuentasbancarias = new HashSet<cuentasbancarias>();
            this.cuentasbancarias1 = new HashSet<cuentasbancarias>();
            this.diaspaginacion = new HashSet<diaspaginacion>();
            this.diaspaginacion1 = new HashSet<diaspaginacion>();
            this.documento_facturacion = new HashSet<documento_facturacion>();
            this.documento_facturacion1 = new HashSet<documento_facturacion>();
            this.documentos_tercero = new HashSet<documentos_tercero>();
            this.documentos_tercero1 = new HashSet<documentos_tercero>();
            this.documentos_vehiculo = new HashSet<documentos_vehiculo>();
            this.documentos_vehiculo1 = new HashSet<documentos_vehiculo>();
            this.encab_documento = new HashSet<encab_documento>();
            this.encab_documento1 = new HashSet<encab_documento>();
            this.encab_documento2 = new HashSet<encab_documento>();
            this.enviocorreo_cumpleanos = new HashSet<enviocorreo_cumpleanos>();
            this.estado_civil = new HashSet<estado_civil>();
            this.estado_civil1 = new HashSet<estado_civil>();
            this.estados_credito = new HashSet<estados_credito>();
            this.estados_credito1 = new HashSet<estados_credito>();
            this.estanterias = new HashSet<estanterias>();
            this.estanterias1 = new HashSet<estanterias>();
            this.estilo_vehiculo = new HashSet<estilo_vehiculo>();
            this.estilo_vehiculo1 = new HashSet<estilo_vehiculo>();
            this.factura_modificada = new HashSet<factura_modificada>();
            this.facturaProforma = new HashSet<facturaProforma>();
            this.facturaProforma1 = new HashSet<facturaProforma>();
            this.fpago_tercero = new HashSet<fpago_tercero>();
            this.fpago_tercero1 = new HashSet<fpago_tercero>();
            this.ftipo_excepciones = new HashSet<ftipo_excepciones>();
            this.ftipo_excepciones1 = new HashSet<ftipo_excepciones>();
            this.gen_tercero = new HashSet<gen_tercero>();
            this.gen_tercero1 = new HashSet<gen_tercero>();
            this.grupo_repuesto = new HashSet<grupo_repuesto>();
            this.grupo_repuesto1 = new HashSet<grupo_repuesto>();
            this.icb_arch_facturacion = new HashSet<icb_arch_facturacion>();
            this.icb_bahia_alistamiento = new HashSet<icb_bahia_alistamiento>();
            this.icb_bahia_alistamiento1 = new HashSet<icb_bahia_alistamiento>();
            this.icb_consecutivo_ot = new HashSet<icb_consecutivo_ot>();
            this.icb_consecutivo_ot1 = new HashSet<icb_consecutivo_ot>();
            this.icb_contacto_tercero = new HashSet<icb_contacto_tercero>();
            this.icb_contacto_tercero1 = new HashSet<icb_contacto_tercero>();
            this.icb_conveperitaje = new HashSet<icb_conveperitaje>();
            this.icb_conveperitaje1 = new HashSet<icb_conveperitaje>();
            this.icb_cuadre_caja = new HashSet<icb_cuadre_caja>();
            this.icb_doc_consecutivos = new HashSet<icb_doc_consecutivos>();
            this.icb_doc_consecutivos1 = new HashSet<icb_doc_consecutivos>();
            this.icb_encabezado_insp_peritaje = new HashSet<icb_encabezado_insp_peritaje>();
            this.icb_encabezado_insp_peritaje1 = new HashSet<icb_encabezado_insp_peritaje>();
            this.icb_inspeccionvehiculos = new HashSet<icb_inspeccionvehiculos>();
            this.icb_piezaperitaje = new HashSet<icb_piezaperitaje>();
            this.icb_piezaperitaje1 = new HashSet<icb_piezaperitaje>();
            this.icb_plan_pago = new HashSet<icb_plan_pago>();
            this.icb_referencia_mov = new HashSet<icb_referencia_mov>();
            this.icb_sedes = new HashSet<icb_sedes>();
            this.icb_sedes1 = new HashSet<icb_sedes>();
            this.icb_sessionlog = new HashSet<icb_sessionlog>();
            this.icb_terceros = new HashSet<icb_terceros>();
            this.icb_terceros1 = new HashSet<icb_terceros>();
            this.icb_tpeventos = new HashSet<icb_tpeventos>();
            this.icb_tpeventos1 = new HashSet<icb_tpeventos>();
            this.icb_tsistemas = new HashSet<icb_tsistemas>();
            this.icb_tsistemas1 = new HashSet<icb_tsistemas>();
            this.icb_vehiculo = new HashSet<icb_vehiculo>();
            this.icb_vehiculo1 = new HashSet<icb_vehiculo>();
            this.icb_vehiculo2 = new HashSet<icb_vehiculo>();
            this.icb_vehiculo_eventos = new HashSet<icb_vehiculo_eventos>();
            this.icb_vehiculo_eventos1 = new HashSet<icb_vehiculo_eventos>();
            this.intentos_fallidos_login = new HashSet<intentos_fallidos_login>();
            this.logCitastallereepprog = new HashSet<logCitastallereepprog>();
            this.logfallosesion = new HashSet<logfallosesion>();
            this.marca_vehiculo = new HashSet<marca_vehiculo>();
            this.marca_vehiculo1 = new HashSet<marca_vehiculo>();
            this.medios_conceptos = new HashSet<medios_conceptos>();
            this.medios_conceptos1 = new HashSet<medios_conceptos>();
            this.medios_formato = new HashSet<medios_formato>();
            this.medios_formato1 = new HashSet<medios_formato>();
            this.mesactualbodega = new HashSet<mesactualbodega>();
            this.metas_asesor = new HashSet<metas_asesor>();
            this.metas_asesor1 = new HashSet<metas_asesor>();
            this.modelo_vehiculo = new HashSet<modelo_vehiculo>();
            this.modelo_vehiculo1 = new HashSet<modelo_vehiculo>();
            this.moneda_conversion = new HashSet<moneda_conversion>();
            this.moneda_conversion1 = new HashSet<moneda_conversion>();
            this.motivobajaactivo = new HashSet<motivobajaactivo>();
            this.motivobajaactivo1 = new HashSet<motivobajaactivo>();
            this.motivosNegacion = new HashSet<motivosNegacion>();
            this.motivosNegacion1 = new HashSet<motivosNegacion>();
            this.mov_contable = new HashSet<mov_contable>();
            this.mov_contable1 = new HashSet<mov_contable>();
            this.movimiento_facturacion = new HashSet<movimiento_facturacion>();
            this.movimiento_facturacion1 = new HashSet<movimiento_facturacion>();
            this.notificacion_llegadacliente = new HashSet<notificacion_llegadacliente>();
            this.pagoscomprobanteegreso = new HashSet<pagoscomprobanteegreso>();
            this.pcotizaciondigital = new HashSet<pcotizaciondigital>();
            this.pcotizaciondigital1 = new HashSet<pcotizaciondigital>();
            this.pperitajeoperacion = new HashSet<pperitajeoperacion>();
            this.pperitajeoperacion1 = new HashSet<pperitajeoperacion>();
            this.prospectos = new HashSet<prospectos>();
            this.prospectos1 = new HashSet<prospectos>();
            this.rdetallesolicitud = new HashSet<rdetallesolicitud>();
            this.rdetallesolicitud1 = new HashSet<rdetallesolicitud>();
            this.recibidotraslados = new HashSet<recibidotraslados>();
            this.recibidotraslados1 = new HashSet<recibidotraslados>();
            this.refpersonales_cred = new HashSet<refpersonales_cred>();
            this.refpersonales_cred1 = new HashSet<refpersonales_cred>();
            this.retencionesbodega = new HashSet<retencionesbodega>();
            this.retencionesbodega1 = new HashSet<retencionesbodega>();
            this.robservacion_solicitud = new HashSet<robservacion_solicitud>();
            this.rordencompra = new HashSet<rordencompra>();
            this.rordencompra1 = new HashSet<rordencompra>();
            this.rordencompra2 = new HashSet<rordencompra>();
            this.rordencompra3 = new HashSet<rordencompra>();
            this.rparametrotipocliente = new HashSet<rparametrotipocliente>();
            this.rparametrotipocliente1 = new HashSet<rparametrotipocliente>();
            this.rseparacionmercancia = new HashSet<rseparacionmercancia>();
            this.rtipocliente = new HashSet<rtipocliente>();
            this.rtipocliente1 = new HashSet<rtipocliente>();
            this.segmentacion = new HashSet<segmentacion>();
            this.segmentacion1 = new HashSet<segmentacion>();
            this.segmento_vehiculo = new HashSet<segmento_vehiculo>();
            this.segmento_vehiculo1 = new HashSet<segmento_vehiculo>();
            this.seguimiento_admin_vh = new HashSet<seguimiento_admin_vh>();
            this.seguimientoseparacion = new HashSet<seguimientoseparacion>();
            this.seguimientotercero = new HashSet<seguimientotercero>();
            this.solicitud_ampliacion_cupo = new HashSet<solicitud_ampliacion_cupo>();
            this.Solicitud_traslado = new HashSet<Solicitud_traslado>();
            this.tablaempresa = new HashSet<tablaempresa>();
            this.tablaempresa1 = new HashSet<tablaempresa>();
            this.tablaretenciones = new HashSet<tablaretenciones>();
            this.tablaretenciones1 = new HashSet<tablaretenciones>();
            this.tareasasignadas = new HashSet<tareasasignadas>();
            this.tareasasignadas1 = new HashSet<tareasasignadas>();
            this.tareasasignadas2 = new HashSet<tareasasignadas>();
            this.tareasasignadas3 = new HashSet<tareasasignadas>();
            this.tcambiobahiatecnico = new HashSet<tcambiobahiatecnico>();
            this.tcategoriainspeccion = new HashSet<tcategoriainspeccion>();
            this.tcategoriainspeccion1 = new HashSet<tcategoriainspeccion>();
            this.tcitamotivocancela = new HashSet<tcitamotivocancela>();
            this.tcitamotivocancela1 = new HashSet<tcitamotivocancela>();
            this.tcitamotivoentrada = new HashSet<tcitamotivoentrada>();
            this.tcitamotivoentrada1 = new HashSet<tcitamotivoentrada>();
            this.tcitasestados = new HashSet<tcitasestados>();
            this.tcitasestados1 = new HashSet<tcitasestados>();
            this.tcitastaller = new HashSet<tcitastaller>();
            this.tcitastaller1 = new HashSet<tcitastaller>();
            this.tcitastaller2 = new HashSet<tcitastaller>();
            this.tcombos = new HashSet<tcombos>();
            this.tconceptoinspeccion = new HashSet<tconceptoinspeccion>();
            this.tconceptoinspeccion1 = new HashSet<tconceptoinspeccion>();
            this.tencabezaorden = new HashSet<tencabezaorden>();
            this.tencabezaorden1 = new HashSet<tencabezaorden>();
            this.tencabezaorden2 = new HashSet<tencabezaorden>();
            this.tencabezaorden_exh = new HashSet<tencabezaorden_exh>();
            this.tencabezaorden_exh1 = new HashSet<tencabezaorden_exh>();
            this.tencabinspeccion = new HashSet<tencabinspeccion>();
            this.tencabinspeccion1 = new HashSet<tencabinspeccion>();
            this.tEstadosOT2 = new HashSet<tEstadosOT2>();
            this.tipificaciontercero = new HashSet<tipificaciontercero>();
            this.tipificaciontercero1 = new HashSet<tipificaciontercero>();
            this.tipo_carroceria = new HashSet<tipo_carroceria>();
            this.tipo_carroceria1 = new HashSet<tipo_carroceria>();
            this.tipo_Checklist = new HashSet<tipo_Checklist>();
            this.tipo_Checklist1 = new HashSet<tipo_Checklist>();
            this.tipo_vehiculo = new HashSet<tipo_vehiculo>();
            this.tipo_vehiculo1 = new HashSet<tipo_vehiculo>();
            this.Tipos_Cartera = new HashSet<Tipos_Cartera>();
            this.Tipos_Cartera1 = new HashSet<Tipos_Cartera>();
            this.tipotramiteasesor = new HashSet<tipotramiteasesor>();
            this.titemopcioninspeccion = new HashSet<titemopcioninspeccion>();
            this.titemopcioninspeccion1 = new HashSet<titemopcioninspeccion>();
            this.titemsinspeccion = new HashSet<titemsinspeccion>();
            this.titemsinspeccion1 = new HashSet<titemsinspeccion>();
            this.tmaximodescuentomo = new HashSet<tmaximodescuentomo>();
            this.tmotivospausa = new HashSet<tmotivospausa>();
            this.tmotivospausa1 = new HashSet<tmotivospausa>();
            this.tmotivosreprogcita = new HashSet<tmotivosreprogcita>();
            this.tordentot = new HashSet<tordentot>();
            this.tot_combo = new HashSet<tot_combo>();
            this.tp_documento1 = new HashSet<tp_documento>();
            this.tp_documento2 = new HashSet<tp_documento>();
            this.tp_subfuente = new HashSet<tp_subfuente>();
            this.tp_subfuente1 = new HashSet<tp_subfuente>();
            this.tparamretenciones = new HashSet<tparamretenciones>();
            this.tparamretenciones1 = new HashSet<tparamretenciones>();
            this.tpcaja_vehiculo = new HashSet<tpcaja_vehiculo>();
            this.tpcaja_vehiculo1 = new HashSet<tpcaja_vehiculo>();
            this.tpmotor_vehiculo = new HashSet<tpmotor_vehiculo>();
            this.tpmotor_vehiculo1 = new HashSet<tpmotor_vehiculo>();
            this.tpservicio_vehiculo = new HashSet<tpservicio_vehiculo>();
            this.tpservicio_vehiculo1 = new HashSet<tpservicio_vehiculo>();
            this.tracking_traslado = new HashSet<tracking_traslado>();
            this.tramitador_vh = new HashSet<tramitador_vh>();
            this.tramitador_vh1 = new HashSet<tramitador_vh>();
            this.trazonesingreso = new HashSet<trazonesingreso>();
            this.trazonesingreso1 = new HashSet<trazonesingreso>();
            this.tseguimientoot = new HashSet<tseguimientoot>();
            this.ttarifastaller = new HashSet<ttarifastaller>();
            this.ttarifastaller1 = new HashSet<ttarifastaller>();
            this.ttecnicos = new HashSet<ttecnicos>();
            this.ttecnicos1 = new HashSet<ttecnicos>();
            this.ttecnicos2 = new HashSet<ttecnicos>();
            this.ttempario = new HashSet<ttempario>();
            this.ttempario1 = new HashSet<ttempario>();
            this.ttipobahia = new HashSet<ttipobahia>();
            this.ttipobahia1 = new HashSet<ttipobahia>();
            this.ttipocita = new HashSet<ttipocita>();
            this.ttrackingorden = new HashSet<ttrackingorden>();
            this.ttrasladosorden = new HashSet<ttrasladosorden>();
            this.ttrasladosorden1 = new HashSet<ttrasladosorden>();
            this.ubicacion_vehiculo = new HashSet<ubicacion_vehiculo>();
            this.ubicacion_vehiculo1 = new HashSet<ubicacion_vehiculo>();
            this.usuarios_caja = new HashSet<usuarios_caja>();
            this.v_hallazgos_novedad = new HashSet<v_hallazgos_novedad>();
            this.v_hallazgos_novedad1 = new HashSet<v_hallazgos_novedad>();
            this.v_hallazgos_partes = new HashSet<v_hallazgos_partes>();
            this.v_hallazgos_partes1 = new HashSet<v_hallazgos_partes>();
            this.v_hallazgos_tp_novedad = new HashSet<v_hallazgos_tp_novedad>();
            this.v_hallazgos_tp_novedad1 = new HashSet<v_hallazgos_tp_novedad>();
            this.v_creditos = new HashSet<v_creditos>();
            this.valores_trasmites = new HashSet<valores_trasmites>();
            this.valores_trasmites1 = new HashSet<valores_trasmites>();
            this.vcodflota = new HashSet<vcodflota>();
            this.vcodflota1 = new HashSet<vcodflota>();
            this.vcotseguimiento = new HashSet<vcotseguimiento>();
            this.vcotseguimiento1 = new HashSet<vcotseguimiento>();
            this.vcotseguimiento2 = new HashSet<vcotseguimiento>();
            this.vdocrequeridos_credito = new HashSet<vdocrequeridos_credito>();
            this.vdocrequeridos_credito1 = new HashSet<vdocrequeridos_credito>();
            this.vdocumentoscredito = new HashSet<vdocumentoscredito>();
            this.vdocumentoscredito1 = new HashSet<vdocumentoscredito>();
            this.vequipamiento = new HashSet<vequipamiento>();
            this.vequipamiento1 = new HashSet<vequipamiento>();
            this.vmodelog = new HashSet<vmodelog>();
            this.vmodelog1 = new HashSet<vmodelog>();
            this.vpedido = new HashSet<vpedido>();
            this.vpedido1 = new HashSet<vpedido>();
            this.vpedido2 = new HashSet<vpedido>();
            this.vpedrepuestos = new HashSet<vpedrepuestos>();
            this.vpedrepuestos1 = new HashSet<vpedrepuestos>();
            this.vpedseguimiento = new HashSet<vpedseguimiento>();
            this.vpedseguimiento1 = new HashSet<vpedseguimiento>();
            this.vvencimientoperitaje = new HashSet<vvencimientoperitaje>();
            this.vvencimientoperitaje1 = new HashSet<vvencimientoperitaje>();
        }
    
        public int user_id { get; set; }
        public int user_numIdent { get; set; }
        public string user_nombre { get; set; }
        public string user_apellido { get; set; }
        public string user_email { get; set; }
        public string user_usuario { get; set; }
        public string user_password { get; set; }
        public string user_confirPassword { get; set; }
        public string user_telefono { get; set; }
        public string user_direccion { get; set; }
        public bool user_estado { get; set; }
        public Nullable<System.DateTime> userfec_creacion { get; set; }
        public Nullable<System.DateTime> userfec_actualizacion { get; set; }
        public Nullable<int> userid_creacion { get; set; }
        public Nullable<int> userid_actualizacion { get; set; }
        public int tpdoc_id { get; set; }
        public int rol_id { get; set; }
        public int ciu_id { get; set; }
        public string user_razoninactivo { get; set; }
        public Nullable<int> userid_licencia { get; set; }
        public Nullable<bool> sesion { get; set; }
        public Nullable<System.DateTime> fechainiplanta { get; set; }
        public Nullable<System.DateTime> fechafinplanta { get; set; }
        public Nullable<int> extension { get; set; }
        public Nullable<int> dpto_id { get; set; }
        public bool cambio_contrasena { get; set; }
        public Nullable<bool> aut_repuestos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acteco_tercero> acteco_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acteco_tercero> acteco_tercero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activoclasificacion> activoclasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activoclasificacion> activoclasificacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activometodo> activometodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activometodo> activometodo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfijos> activosfijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfijos> activosfijos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfijos> activosfijos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfubicacion> activosfubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activosfubicacion> activosfubicacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adecuaciones_peritaje> adecuaciones_peritaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aencab_auditoriainv> aencab_auditoriainv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aencab_auditoriainv> aencab_auditoriainv1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda_asesor> agenda_asesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda_asesor> agenda_asesor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda_demos> agenda_demos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda_mensajero> agenda_mensajero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda_mensajero> agenda_mensajero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alertaasesor> alertaasesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alertaasesor> alertaasesor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amodificaciones_auditoriainv> amodificaciones_auditoriainv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amodificaciones_extra_auditoriainv> amodificaciones_extra_auditoriainv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionclasificacion> amortizacionclasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionclasificacion> amortizacionclasificacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfijos> amortizacionfijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfijos> amortizacionfijos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfijos> amortizacionfijos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfubicacion> amortizacionfubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacionfubicacion> amortizacionfubicacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apareja_auditoriainv> apareja_auditoriainv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apareja_auditoriainv> apareja_auditoriainv1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archListaPrecios> archListaPrecios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asesor_log> asesor_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asesor_log> asesor_log1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion> asignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<autorizaciones> autorizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<autorizaciones> autorizaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahia_alistamiento_exh> bahia_alistamiento_exh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahia_alistamiento_exh> bahia_alistamiento_exh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacoraExcepcionFactura> bitacoraExcepcionFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacoraExcepcionFactura> bitacoraExcepcionFactura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodega_concesionario> bodega_concesionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodega_concesionario> bodega_concesionario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodega_usuario_visualizacion> bodega_usuario_visualizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja_menor> caja_menor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja_menor> caja_menor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja_menor_bodega> caja_menor_bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja_menor_bodega> caja_menor_bodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cambioubicacionveh> cambioubicacionveh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargacirculares> cargacirculares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<centro_costo> centro_costo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasificacion_cliente> clasificacion_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasificacion_cliente> clasificacion_cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasificacion_repuesto> clasificacion_repuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasificacion_repuesto> clasificacion_repuesto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasificacion_vehiculo> clasificacion_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clasificacion_vehiculo> clasificacion_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<color_vehiculo> color_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<color_vehiculo> color_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_campinspecciontaller> crm_campinspecciontaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_campinspecciontaller> crm_campinspecciontaller1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_campvintaller> crm_campvintaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_encuesta_respuestas> crm_encuesta_respuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_encuestas> crm_encuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_encuestas> crm_encuestas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cruce_documentos> cruce_documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasbancarias> cuentasbancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasbancarias> cuentasbancarias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diaspaginacion> diaspaginacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diaspaginacion> diaspaginacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento_facturacion> documento_facturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento_facturacion> documento_facturacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_tercero> documentos_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_tercero> documentos_tercero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_vehiculo> documentos_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_vehiculo> documentos_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encab_documento> encab_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encab_documento> encab_documento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encab_documento> encab_documento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enviocorreo_cumpleanos> enviocorreo_cumpleanos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estado_civil> estado_civil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estado_civil> estado_civil1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estados_credito> estados_credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estados_credito> estados_credito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estanterias> estanterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estanterias> estanterias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estilo_vehiculo> estilo_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estilo_vehiculo> estilo_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_modificada> factura_modificada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaProforma> facturaProforma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaProforma> facturaProforma1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fpago_tercero> fpago_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fpago_tercero> fpago_tercero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftipo_excepciones> ftipo_excepciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftipo_excepciones> ftipo_excepciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gen_tercero> gen_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gen_tercero> gen_tercero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_repuesto> grupo_repuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_repuesto> grupo_repuesto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_arch_facturacion> icb_arch_facturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_bahia_alistamiento> icb_bahia_alistamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_bahia_alistamiento> icb_bahia_alistamiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_consecutivo_ot> icb_consecutivo_ot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_consecutivo_ot> icb_consecutivo_ot1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_contacto_tercero> icb_contacto_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_contacto_tercero> icb_contacto_tercero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_conveperitaje> icb_conveperitaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_conveperitaje> icb_conveperitaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_cuadre_caja> icb_cuadre_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_doc_consecutivos> icb_doc_consecutivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_doc_consecutivos> icb_doc_consecutivos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_encabezado_insp_peritaje> icb_encabezado_insp_peritaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_encabezado_insp_peritaje> icb_encabezado_insp_peritaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_inspeccionvehiculos> icb_inspeccionvehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_piezaperitaje> icb_piezaperitaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_piezaperitaje> icb_piezaperitaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_plan_pago> icb_plan_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_referencia_mov> icb_referencia_mov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_sedes> icb_sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_sedes> icb_sedes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_sessionlog> icb_sessionlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_terceros> icb_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_terceros> icb_terceros1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_tpeventos> icb_tpeventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_tpeventos> icb_tpeventos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_tsistemas> icb_tsistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_tsistemas> icb_tsistemas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo> icb_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo> icb_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo> icb_vehiculo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo_eventos> icb_vehiculo_eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<icb_vehiculo_eventos> icb_vehiculo_eventos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<intentos_fallidos_login> intentos_fallidos_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logCitastallereepprog> logCitastallereepprog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logfallosesion> logfallosesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marca_vehiculo> marca_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marca_vehiculo> marca_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medios_conceptos> medios_conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medios_conceptos> medios_conceptos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medios_formato> medios_formato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medios_formato> medios_formato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesactualbodega> mesactualbodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metas_asesor> metas_asesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metas_asesor> metas_asesor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelo_vehiculo> modelo_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelo_vehiculo> modelo_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moneda_conversion> moneda_conversion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moneda_conversion> moneda_conversion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<motivobajaactivo> motivobajaactivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<motivobajaactivo> motivobajaactivo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<motivosNegacion> motivosNegacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<motivosNegacion> motivosNegacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mov_contable> mov_contable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mov_contable> mov_contable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_facturacion> movimiento_facturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_facturacion> movimiento_facturacion1 { get; set; }
        public virtual nom_ciudad nom_ciudad { get; set; }
        public virtual nom_departamento nom_departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion_llegadacliente> notificacion_llegadacliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagoscomprobanteegreso> pagoscomprobanteegreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pcotizaciondigital> pcotizaciondigital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pcotizaciondigital> pcotizaciondigital1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pperitajeoperacion> pperitajeoperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pperitajeoperacion> pperitajeoperacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospectos> prospectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospectos> prospectos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rdetallesolicitud> rdetallesolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rdetallesolicitud> rdetallesolicitud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibidotraslados> recibidotraslados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibidotraslados> recibidotraslados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<refpersonales_cred> refpersonales_cred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<refpersonales_cred> refpersonales_cred1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<retencionesbodega> retencionesbodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<retencionesbodega> retencionesbodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<robservacion_solicitud> robservacion_solicitud { get; set; }
        public virtual rols rols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rordencompra> rordencompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rordencompra> rordencompra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rordencompra> rordencompra2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rordencompra> rordencompra3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rparametrotipocliente> rparametrotipocliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rparametrotipocliente> rparametrotipocliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rseparacionmercancia> rseparacionmercancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rtipocliente> rtipocliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rtipocliente> rtipocliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segmentacion> segmentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segmentacion> segmentacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segmento_vehiculo> segmento_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segmento_vehiculo> segmento_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimiento_admin_vh> seguimiento_admin_vh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimientoseparacion> seguimientoseparacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimientotercero> seguimientotercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud_ampliacion_cupo> solicitud_ampliacion_cupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_traslado> Solicitud_traslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablaempresa> tablaempresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablaempresa> tablaempresa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablaretenciones> tablaretenciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablaretenciones> tablaretenciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareasasignadas> tareasasignadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareasasignadas> tareasasignadas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareasasignadas> tareasasignadas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareasasignadas> tareasasignadas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcambiobahiatecnico> tcambiobahiatecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcategoriainspeccion> tcategoriainspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcategoriainspeccion> tcategoriainspeccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitamotivocancela> tcitamotivocancela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitamotivocancela> tcitamotivocancela1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitamotivoentrada> tcitamotivoentrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitamotivoentrada> tcitamotivoentrada1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitasestados> tcitasestados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitasestados> tcitasestados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitastaller> tcitastaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitastaller> tcitastaller1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitastaller> tcitastaller2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcombos> tcombos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tconceptoinspeccion> tconceptoinspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tconceptoinspeccion> tconceptoinspeccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabezaorden> tencabezaorden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabezaorden> tencabezaorden1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabezaorden> tencabezaorden2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabezaorden_exh> tencabezaorden_exh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabezaorden_exh> tencabezaorden_exh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabinspeccion> tencabinspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tencabinspeccion> tencabinspeccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEstadosOT2> tEstadosOT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipificaciontercero> tipificaciontercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipificaciontercero> tipificaciontercero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_carroceria> tipo_carroceria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_carroceria> tipo_carroceria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_Checklist> tipo_Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_Checklist> tipo_Checklist1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_vehiculo> tipo_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_vehiculo> tipo_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipos_Cartera> Tipos_Cartera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipos_Cartera> Tipos_Cartera1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipotramiteasesor> tipotramiteasesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titemopcioninspeccion> titemopcioninspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titemopcioninspeccion> titemopcioninspeccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titemsinspeccion> titemsinspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titemsinspeccion> titemsinspeccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaximodescuentomo> tmaximodescuentomo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmotivospausa> tmotivospausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmotivospausa> tmotivospausa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmotivosreprogcita> tmotivosreprogcita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tordentot> tordentot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tot_combo> tot_combo { get; set; }
        public virtual tp_documento tp_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_documento> tp_documento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_documento> tp_documento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_subfuente> tp_subfuente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_subfuente> tp_subfuente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tparamretenciones> tparamretenciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tparamretenciones> tparamretenciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpcaja_vehiculo> tpcaja_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpcaja_vehiculo> tpcaja_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpmotor_vehiculo> tpmotor_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpmotor_vehiculo> tpmotor_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpservicio_vehiculo> tpservicio_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpservicio_vehiculo> tpservicio_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tracking_traslado> tracking_traslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tramitador_vh> tramitador_vh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tramitador_vh> tramitador_vh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trazonesingreso> trazonesingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trazonesingreso> trazonesingreso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tseguimientoot> tseguimientoot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttarifastaller> ttarifastaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttarifastaller> ttarifastaller1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttecnicos> ttecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttecnicos> ttecnicos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttecnicos> ttecnicos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttempario> ttempario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttempario> ttempario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttipobahia> ttipobahia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttipobahia> ttipobahia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttipocita> ttipocita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttrackingorden> ttrackingorden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttrasladosorden> ttrasladosorden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttrasladosorden> ttrasladosorden1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicacion_vehiculo> ubicacion_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicacion_vehiculo> ubicacion_vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_caja> usuarios_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_novedad> v_hallazgos_novedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_novedad> v_hallazgos_novedad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_partes> v_hallazgos_partes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_partes> v_hallazgos_partes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_tp_novedad> v_hallazgos_tp_novedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_tp_novedad> v_hallazgos_tp_novedad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_creditos> v_creditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valores_trasmites> valores_trasmites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valores_trasmites> valores_trasmites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vcodflota> vcodflota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vcodflota> vcodflota1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vcotseguimiento> vcotseguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vcotseguimiento> vcotseguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vcotseguimiento> vcotseguimiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vdocrequeridos_credito> vdocrequeridos_credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vdocrequeridos_credito> vdocrequeridos_credito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vdocumentoscredito> vdocumentoscredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vdocumentoscredito> vdocumentoscredito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vequipamiento> vequipamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vequipamiento> vequipamiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vmodelog> vmodelog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vmodelog> vmodelog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedido> vpedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedido> vpedido1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedido> vpedido2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedrepuestos> vpedrepuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedrepuestos> vpedrepuestos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedseguimiento> vpedseguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpedseguimiento> vpedseguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vvencimientoperitaje> vvencimientoperitaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vvencimientoperitaje> vvencimientoperitaje1 { get; set; }
    }
}
