//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_hallazgos_novedad
    {
        public int hll_id { get; set; }
        public Nullable<decimal> hll_dimension { get; set; }
        public Nullable<int> hllp_id { get; set; }
        public Nullable<int> hlltp_id { get; set; }
        public Nullable<int> hll_usuela { get; set; }
        public Nullable<System.DateTime> hll_fecela { get; set; }
        public Nullable<int> hll_usumod { get; set; }
        public Nullable<System.DateTime> hll_fecmod { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual v_hallazgos_partes v_hallazgos_partes { get; set; }
        public virtual v_hallazgos_tp_novedad v_hallazgos_tp_novedad { get; set; }
    }
}
