//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_hallazgos_partes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public v_hallazgos_partes()
        {
            this.v_hallazgos_novedad = new HashSet<v_hallazgos_novedad>();
        }
    
        public int hllp_id { get; set; }
        public string hllp_parte { get; set; }
        public Nullable<bool> hllp_hablt { get; set; }
        public Nullable<int> hllp_usuela { get; set; }
        public Nullable<System.DateTime> hllp_fecela { get; set; }
        public Nullable<int> hllp_usumod { get; set; }
        public Nullable<System.DateTime> hllp_fecmod { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_hallazgos_novedad> v_hallazgos_novedad { get; set; }
    }
}
