//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class valores_trasmites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public valores_trasmites()
        {
            this.valortramitebodega = new HashSet<valortramitebodega>();
        }
    
        public int idvalor { get; set; }
        public Nullable<int> ciudad_id { get; set; }
        public Nullable<decimal> sijin { get; set; }
        public Nullable<decimal> traspaso { get; set; }
        public Nullable<decimal> tarjeta { get; set; }
        public Nullable<decimal> runt { get; set; }
        public Nullable<decimal> traslado_cuenta { get; set; }
        public Nullable<decimal> radicacion_cuenta { get; set; }
        public Nullable<decimal> consig_minist_tte { get; set; }
        public Nullable<decimal> prenda { get; set; }
        public Nullable<decimal> serv_tramitador { get; set; }
        public Nullable<decimal> antec_pazysalvo { get; set; }
        public Nullable<decimal> estampillas { get; set; }
        public Nullable<decimal> semaforizacion { get; set; }
        public Nullable<decimal> tradicion { get; set; }
        public Nullable<decimal> copia_factura { get; set; }
        public Nullable<decimal> sistematizacion_impuestos { get; set; }
        public Nullable<decimal> derechos_transito { get; set; }
        public Nullable<decimal> sistematizacion { get; set; }
        public Nullable<decimal> cert_transito { get; set; }
        public string bodega { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
    
        public virtual nom_ciudad nom_ciudad { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valortramitebodega> valortramitebodega { get; set; }
    }
}
