//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdescuentoscondicionados
    {
        public int id { get; set; }
        public string circular { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public Nullable<int> tipo { get; set; }
        public string modelo { get; set; }
        public int anomodelo { get; set; }
        public decimal descuento { get; set; }
        public Nullable<System.DateTime> feccompradesde { get; set; }
        public Nullable<System.DateTime> feccomprahasta { get; set; }
        public Nullable<decimal> descuentoadicional { get; set; }
        public Nullable<System.DateTime> fecadicional { get; set; }
        public Nullable<decimal> descuentopie { get; set; }
        public Nullable<decimal> bonoretoma { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public Nullable<bool> estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<System.DateTime> fecventaini { get; set; }
        public Nullable<System.DateTime> fecventafin { get; set; }
        public bool aplicafota { get; set; }
        public bool esdetal { get; set; }
        public string Notas { get; set; }
    
        public virtual modelo_vehiculo modelo_vehiculo { get; set; }
        public virtual vtipobono vtipobono { get; set; }
    }
}
