//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdocumentoscredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vdocumentoscredito()
        {
            this.vdocrequeridos_credito = new HashSet<vdocrequeridos_credito>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool obligatorio { get; set; }
        public bool estado { get; set; }
        public string razon_inactivo { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<int> userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> userid_actualizacion { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vdocrequeridos_credito> vdocrequeridos_credito { get; set; }
    }
}
