//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vhorarios
    {
        public int id { get; set; }
        public Nullable<System.TimeSpan> horainidia { get; set; }
        public Nullable<System.TimeSpan> horafindia { get; set; }
        public Nullable<System.TimeSpan> horainitarde { get; set; }
        public Nullable<System.TimeSpan> horafintarde { get; set; }
        public Nullable<bool> dia1 { get; set; }
        public Nullable<bool> dia2 { get; set; }
        public Nullable<bool> dia3 { get; set; }
        public Nullable<bool> dia4 { get; set; }
        public Nullable<bool> dia5 { get; set; }
        public Nullable<bool> dia6 { get; set; }
        public Nullable<bool> dia7 { get; set; }
        public Nullable<bool> semana { get; set; }
        public string tipoagenda { get; set; }
        public string demo { get; set; }
        public Nullable<int> asesor { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public int userid_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public Nullable<bool> estado { get; set; }
        public string razon_inactivo { get; set; }
        public int concesionaroid { get; set; }
    }
}
