//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int bodega { get; set; }
        public string bodccs_nombre { get; set; }
        public string codigo { get; set; }
        public string ref_descripcion { get; set; }
        public short ano { get; set; }
        public short mes { get; set; }
        public decimal can_ini { get; set; }
        public decimal can_ent { get; set; }
        public decimal can_sal { get; set; }
        public decimal cos_ini { get; set; }
        public decimal cos_ent { get; set; }
        public decimal cos_sal { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<decimal> CostoStock { get; set; }
        public string modulo { get; set; }
        public Nullable<decimal> CostoProm { get; set; }
        public string ClasifABC { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<System.DateTime> fechaUltimacompra { get; set; }
        public string Ubicacion { get; set; }
    }
}
