//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vlisretomas
    {
        public string marca { get; set; }
        public string estilo { get; set; }
        public string anoModelo { get; set; }
        public string precio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int userid_creacion { get; set; }
        public int id { get; set; }
    }
}
