//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpedrepuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vpedrepuestos()
        {
            this.tcitarepuestos = new HashSet<tcitarepuestos>();
        }
    
        public int id { get; set; }
        public int pedido_id { get; set; }
        public string referencia { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> vrunitario { get; set; }
        public Nullable<decimal> vrtotal { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public Nullable<int> user_idactualizacion { get; set; }
        public Nullable<bool> obsequio { get; set; }
        public bool facturado { get; set; }
        public Nullable<int> idtipo { get; set; }
        public Nullable<int> numfactura { get; set; }
        public bool instalado { get; set; }
        public Nullable<bool> respuestaInterna { get; set; }
        public string observacionresinterva { get; set; }
        public Nullable<int> idcentro { get; set; }
        public Nullable<int> tipotarifa { get; set; }
        public Nullable<float> iva { get; set; }
        public Nullable<float> descuento { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual centro_costo centro_costo { get; set; }
        public virtual icb_referencia icb_referencia { get; set; }
        public virtual rtipocliente rtipocliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcitarepuestos> tcitarepuestos { get; set; }
        public virtual tp_doc_registros tp_doc_registros { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual vpedido vpedido { get; set; }
    }
}
