//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpedretoma
    {
        public int id { get; set; }
        public int pedido_id { get; set; }
        public string placa { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string modelo { get; set; }
        public Nullable<decimal> kilometraje { get; set; }
        public Nullable<bool> obligaciones { get; set; }
        public Nullable<decimal> valor_obligacion { get; set; }
    
        public virtual vpedido vpedido { get; set; }
    }
}
