//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpedpago
    {
        public int id { get; set; }
        public int idpedido { get; set; }
        public int condicion { get; set; }
        public int seq { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> nit { get; set; }
        public Nullable<System.DateTime> fecpago { get; set; }
        public string observaciones { get; set; }
        public string tipo_doc { get; set; }
        public Nullable<int> numero_doc { get; set; }
        public Nullable<int> banco { get; set; }
    
        public virtual icb_unidad_financiera icb_unidad_financiera { get; set; }
        public virtual vformapago vformapago { get; set; }
        public virtual vpedido vpedido { get; set; }
    }
}
