//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vppolizas
    {
        public int id { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public string modelo { get; set; }
        public int modeloano { get; set; }
        public string Descripcion { get; set; }
        public decimal precio { get; set; }
    }
}
