//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admonot_garantia
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string fecha2 { get; set; }
        public string codigoentrada { get; set; }
        public string cedula { get; set; }
        public string Nombre_cliente { get; set; }
        public string placa { get; set; }
        public string vin { get; set; }
        public Nullable<int> estadoorden { get; set; }
        public string nomEstado { get; set; }
        public string bodega { get; set; }
        public string estadodos { get; set; }
    }
}
