//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_browser_referencias
    {
        public string ref_codigo { get; set; }
        public string ref_descripcion { get; set; }
        public string grupo_id { get; set; }
        public string grupo_repuesto_nombre { get; set; }
        public Nullable<int> clasificacion_id { get; set; }
        public string clarpto_nombre { get; set; }
        public string linea_id { get; set; }
        public string Descripcion { get; set; }
        public string familia_id { get; set; }
        public string familia_nombre { get; set; }
        public string grupo_nombre { get; set; }
        public string subgrupo_nombre { get; set; }
        public bool ref_estado { get; set; }
        public string nombre_estado { get; set; }
        public decimal precio_garantia { get; set; }
        public string precio_garantia_string { get; set; }
        public string modulo { get; set; }
        public string alias { get; set; }
    }
}
