//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_contabilidad
    {
        public int bodega { get; set; }
        public string bodccs_cod { get; set; }
        public string bodccs_nombre { get; set; }
        public string prefijo { get; set; }
        public string tpdoc_nombre { get; set; }
        public int idencabezado { get; set; }
        public long numero { get; set; }
        public string doc_tercero { get; set; }
        public string prinom_tercero { get; set; }
        public string apellido_tercero { get; set; }
        public int nit { get; set; }
        public Nullable<int> idparametronombre { get; set; }
        public string descripcion_parametro { get; set; }
        public Nullable<int> cuenta { get; set; }
        public string cntpuc_numero { get; set; }
        public string cntpuc_descp { get; set; }
        public Nullable<int> centro { get; set; }
        public string centcst_nombre { get; set; }
        public Nullable<decimal> debito { get; set; }
        public Nullable<decimal> credito { get; set; }
        public Nullable<decimal> debitoniif { get; set; }
        public Nullable<decimal> creditoniif { get; set; }
        public Nullable<System.DateTime> fec { get; set; }
        public string fecha2 { get; set; }
        public string clase { get; set; }
        public Nullable<int> clase2 { get; set; }
        public string grupo { get; set; }
        public Nullable<int> grupo2 { get; set; }
        public string xcuenta { get; set; }
        public Nullable<int> xcuenta2 { get; set; }
        public string subcuenta { get; set; }
        public Nullable<int> subcuenta2 { get; set; }
        public Nullable<int> tpdoc_id { get; set; }
    }
}
