//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cartera_factura_inicio
    {
        public Nullable<decimal> valortotal { get; set; }
        public Nullable<decimal> valoraplicado { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public int nit { get; set; }
        public string doc_tercero { get; set; }
        public string prinom_tercero { get; set; }
        public string segnom_tercero { get; set; }
        public string apellido_tercero { get; set; }
        public string segapellido_tercero { get; set; }
        public Nullable<int> tipotercero { get; set; }
        public string razon_social { get; set; }
        public string telf_tercero { get; set; }
        public string celular_tercero { get; set; }
        public bool tercero_estado { get; set; }
        public Nullable<int> sw { get; set; }
    }
}
