//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRMgeneral
    {
        public int cltercero_id { get; set; }
        public int tercero_id { get; set; }
        public string doc_tercero { get; set; }
        public Nullable<int> tpdoc_id { get; set; }
        public string tipo { get; set; }
        public string tpdoc_nombre { get; set; }
        public Nullable<System.DateTime> tercerofec_creacion { get; set; }
        public string tercero { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> gentercero_id { get; set; }
        public string gentercero_nombre { get; set; }
        public Nullable<System.DateTime> fec_nacimiento { get; set; }
        public string celular_tercero { get; set; }
        public string telf_tercero { get; set; }
        public string email_tercero { get; set; }
        public string Segmentacion { get; set; }
        public string plan_mayor { get; set; }
        public Nullable<int> marcvh_id { get; set; }
        public string marcvh_nombre { get; set; }
        public string modvh_codigo { get; set; }
        public string ref_descripcion { get; set; }
        public string Descripcion { get; set; }
        public string colvh_id { get; set; }
        public string colvh_nombre { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> Fecha_venta { get; set; }
    }
}
