//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_conceptosFiltradosGroup
    {
        public int ano { get; set; }
        public int formato { get; set; }
        public int concepto { get; set; }
        public string operacion { get; set; }
        public int idvalor { get; set; }
        public int tipomovimiento { get; set; }
        public int nit { get; set; }
        public Nullable<decimal> SubDebito { get; set; }
        public Nullable<decimal> SumaCredito { get; set; }
        public Nullable<decimal> SumaBase { get; set; }
        public Nullable<decimal> SumaSaldo { get; set; }
    }
}
