//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_control_pedidos
    {
        public int id_detalle { get; set; }
        public int esta_pedido { get; set; }
        public int id { get; set; }
        public int idbodega { get; set; }
        public string bodccs_nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public string clienteCedula { get; set; }
        public string clienteNombre { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string usuarioSolicitud { get; set; }
        public string codreferencia { get; set; }
        public string referencia { get; set; }
        public string referenciasSolicitadas { get; set; }
        public string Detalle { get; set; }
        public string clasificacion_ABC { get; set; }
        public int ref_cantidad_min { get; set; }
        public Nullable<decimal> stock { get; set; }
        public int can_backoprder { get; set; }
        public int cantidad_recibida { get; set; }
        public int cantidad_pedida { get; set; }
        public Nullable<int> idtipo_compra { get; set; }
        public string tipo_compra { get; set; }
        public int cantidad_clasificacio { get; set; }
        public string responsable { get; set; }
        public string vehiculo { get; set; }
        public Nullable<System.DateTime> fecha_separacion { get; set; }
        public Nullable<int> estado_solicitud { get; set; }
        public Nullable<int> separacion { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> idseparacion { get; set; }
        public Nullable<int> No_de_orden { get; set; }
        public string Descripcion { get; set; }
        public string listaanticipos { get; set; }
    }
}
