//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cartera_edades_cuenta
    {
        public int cuenta { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public int vencido { get; set; }
        public Nullable<int> dias_vencido { get; set; }
        public int vencido_uno_a_treinta { get; set; }
        public int vencido_treintauno_a_sesenta { get; set; }
        public int vencido_sesentauno_a_noventa { get; set; }
        public int vencido_noventauno_a_cientoveinte { get; set; }
        public int mayor_cientoveinte { get; set; }
    }
}
