//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cargarMensajeria
    {
        public int detalle { get; set; }
        public long numero { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public string estado { get; set; }
        public string tipo_prioridad { get; set; }
        public string tipo_transporte { get; set; }
        public string prinom_tercero { get; set; }
        public string apellido_tercero { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> origen_bodega { get; set; }
        public Nullable<int> destino_bodega { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public int id { get; set; }
        public int userid_creacion { get; set; }
        public string bodccs_nombre { get; set; }
        public string user_nombre { get; set; }
        public string user_apellido { get; set; }
        public Nullable<int> traslado { get; set; }
        public Nullable<int> recibotraslado { get; set; }
        public Nullable<int> tipo_estado { get; set; }
    }
}
