//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cargadelima
    {
        public string vin { get; set; }
        public Nullable<System.DateTime> fecha_factura_css { get; set; }
        public System.DateTime fechaevento { get; set; }
        public Nullable<int> propietario { get; set; }
        public string nombrecliente { get; set; }
        public Nullable<decimal> vrtotal { get; set; }
        public Nullable<int> numfactura { get; set; }
        public string plac_vh { get; set; }
        public Nullable<int> id_bod { get; set; }
    }
}
