//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_doccartera
    {
        public int tipo { get; set; }
        public string prefijo { get; set; }
        public long numero { get; set; }
        public int nit { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public decimal valor_total { get; set; }
        public decimal valor_aplicado { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<int> tipofacturacion { get; set; }
    }
}
