//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_historialtaller
    {
        public int orden_taller { get; set; }
        public string placa { get; set; }
        public string ref_descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string razoz_ingreso { get; set; }
        public long kilometraje { get; set; }
        public string Cliente { get; set; }
    }
}
