//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_historial_vehiculos_nuevos
    {
        public string plan_mayor { get; set; }
        public string user_nombre { get; set; }
        public string user_apellido { get; set; }
        public string fechaPedido { get; set; }
        public string FechaCompra { get; set; }
        public Nullable<System.DateTime> icbvhfec_actualizacion { get; set; }
        public string fechaActualizacion { get; set; }
        public string bodccs_nombre { get; set; }
        public Nullable<decimal> cot_numcotizacion { get; set; }
        public string numerocotizacion { get; set; }
        public Nullable<int> numero { get; set; }
        public string numeropedido { get; set; }
        public string modelovehiculo { get; set; }
        public string placavehiculo { get; set; }
        public Nullable<int> flota { get; set; }
        public string flota2 { get; set; }
        public string modvh_nombre { get; set; }
        public string segvh_nombre { get; set; }
        public string poliza { get; set; }
        public Nullable<System.DateTime> fechaevento { get; set; }
        public string estado_ve { get; set; }
        public string ParametroRecepcionBodega { get; set; }
        public string DescripcionRecepcionBodega { get; set; }
        public Nullable<System.DateTime> FechaRecepcionBodega { get; set; }
        public string FechaRecepcion { get; set; }
        public Nullable<int> IdEventoRecepcionBodega { get; set; }
        public string ideventoBodega { get; set; }
        public Nullable<int> IdTecnicoRecepcionBodega { get; set; }
        public string idenTecnico { get; set; }
        public string NombreTecnicoRecepcionBodega { get; set; }
        public Nullable<int> diasInventario { get; set; }
        public string diasInventario2 { get; set; }
        public Nullable<System.DateTime> fecha_Evento { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<bool> recepcion { get; set; }
        public string idBodega { get; set; }
        public string vin { get; set; }
        public int anio { get; set; }
        public string fechaCotizacion { get; set; }
        public string nombreCliente { get; set; }
        public string nombreProspecto { get; set; }
        public string color { get; set; }
        public string ubicacion { get; set; }
        public string FechaEntrega { get; set; }
        public string FechaSoat { get; set; }
        public string numerosoat { get; set; }
    }
}
