//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_item_inventario
    {
        public string ref_codigo { get; set; }
        public string ref_descripcion { get; set; }
        public int bodega { get; set; }
        public string nombreBodega { get; set; }
        public Nullable<int> cantidad_comprometida { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public string clasificacion_ABC { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public decimal stock { get; set; }
        public decimal costo_emergencia { get; set; }
        public string ubicacion { get; set; }
    }
}
