//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_inventario_por_empresa
    {
        public string codigo { get; set; }
        public short ano { get; set; }
        public short mes { get; set; }
        public Nullable<decimal> can_ini { get; set; }
        public Nullable<decimal> can_ent { get; set; }
        public Nullable<decimal> can_sal { get; set; }
        public Nullable<decimal> cos_ini { get; set; }
        public Nullable<decimal> cos_ent { get; set; }
        public Nullable<decimal> cos_sal { get; set; }
        public Nullable<decimal> can_vta { get; set; }
        public Nullable<decimal> cos_vta { get; set; }
        public Nullable<decimal> val_vta { get; set; }
        public Nullable<decimal> can_dev_vta { get; set; }
        public Nullable<decimal> cos_dev_vta { get; set; }
        public Nullable<decimal> val_dev { get; set; }
        public Nullable<decimal> can_com { get; set; }
        public Nullable<decimal> cos_com { get; set; }
        public Nullable<decimal> can_dev_com { get; set; }
        public Nullable<decimal> cos_dev_com { get; set; }
        public Nullable<decimal> can_otr_ent { get; set; }
        public Nullable<decimal> cos_otr_ent { get; set; }
        public Nullable<decimal> can_otr_sal { get; set; }
        public Nullable<decimal> cos_otr_sal { get; set; }
        public Nullable<decimal> can_tra { get; set; }
        public Nullable<decimal> cos_tra { get; set; }
        public Nullable<decimal> sub_cos { get; set; }
        public Nullable<decimal> baj_cos { get; set; }
        public Nullable<int> nro_vta { get; set; }
        public Nullable<int> nro_dev_vta { get; set; }
        public Nullable<int> nro_com { get; set; }
        public Nullable<int> nro_dev_com { get; set; }
        public Nullable<int> nro_ped { get; set; }
        public Nullable<decimal> can_ped { get; set; }
    }
}
