//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lista_vh_nuevos
    {
        public int id { get; set; }
        public string lista { get; set; }
        public string concepto { get; set; }
        public string ano { get; set; }
        public string mes { get; set; }
        public string codigo_modelo { get; set; }
        public string descripcion { get; set; }
        public string planmayor { get; set; }
        public string anio_modelo { get; set; }
        public string preciolista { get; set; }
        public string precioespecial { get; set; }
    }
}
