//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lista_referencias
    {
        public string ref_codigo { get; set; }
        public string ref_descripcion { get; set; }
        public string iva { get; set; }
        public string precio_venta { get; set; }
        public string costo_promedio { get; set; }
        public string precio_iva { get; set; }
        public bool ref_estado { get; set; }
        public string modulo { get; set; }
    }
}
