//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_migraciones_parametrizadas
    {
        public int id { get; set; }
        public string nombre_migracion { get; set; }
        public string nombre_tabla { get; set; }
        public string columnas { get; set; }
        public string constraints { get; set; }
    }
}
