//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_matriz_mantenimiento_2
    {
        public int modgeneral { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
        public Nullable<decimal> C6 { get; set; }
        public Nullable<decimal> C7 { get; set; }
        public Nullable<decimal> C8 { get; set; }
        public Nullable<decimal> C9 { get; set; }
        public Nullable<decimal> C10 { get; set; }
        public Nullable<decimal> C11 { get; set; }
        public Nullable<decimal> C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<decimal> C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public Nullable<decimal> C16 { get; set; }
        public Nullable<decimal> C17 { get; set; }
        public Nullable<decimal> C18 { get; set; }
        public Nullable<decimal> C19 { get; set; }
        public Nullable<decimal> C20 { get; set; }
    }
}
