//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_matriculas
    {
        public System.DateTime fechaevento { get; set; }
        public string planmayor { get; set; }
        public int id_tpevento { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public string bodccs_nombre { get; set; }
        public Nullable<int> asesor_id { get; set; }
        public string Asesor { get; set; }
        public Nullable<bool> nuevo { get; set; }
        public Nullable<bool> usado { get; set; }
        public string modvh_nombre { get; set; }
        public string colvh_nombre { get; set; }
        public int anio_vh { get; set; }
        public string tipo { get; set; }
    }
}
