//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ordenes_taller
    {
        public string tercero { get; set; }
        public int numero_orden { get; set; }
        public string bodccs_nombre { get; set; }
        public long kilometraje { get; set; }
        public string user_nombre { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string estado { get; set; }
        public string tipo_orden { get; set; }
        public string tipo_operacion { get; set; }
        public int orden { get; set; }
        public string operacion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public decimal valorunitario { get; set; }
        public Nullable<decimal> pordescuento { get; set; }
        public Nullable<decimal> poriva { get; set; }
        public string plan_mantenimiento { get; set; }
    }
}
