//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_operaciones_vh
    {
        public bool estado { get; set; }
        public int ot_id { get; set; }
        public Nullable<int> idtecnico { get; set; }
        public string placa { get; set; }
        public Nullable<int> tsis_id { get; set; }
        public string tsis_sistema { get; set; }
        public Nullable<int> tsope_id { get; set; }
        public string codigo { get; set; }
        public string operacion { get; set; }
        public string referencia { get; set; }
        public int cant_sistema { get; set; }
        public Nullable<float> tiempo { get; set; }
        public Nullable<decimal> costo_tempario { get; set; }
        public Nullable<decimal> precio_tempario { get; set; }
        public Nullable<decimal> precio_repuesto { get; set; }
        public string precio_repuesto_string { get; set; }
        public Nullable<decimal> precio_total { get; set; }
        public string precio_total_string { get; set; }
        public string tsis_estadovh { get; set; }
        public string tinsvh_estado { get; set; }
        public Nullable<int> tsot_id { get; set; }
        public Nullable<int> mnobra_id { get; set; }
        public Nullable<int> tinsvh_id { get; set; }
        public Nullable<System.DateTime> tinsvh_fecenviosms { get; set; }
        public Nullable<bool> tinsvh_resp_sms { get; set; }
        public string tinsvh_observacion { get; set; }
    }
}
