//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_prefacturas
    {
        public int idencabezado { get; set; }
        public bool prefactura { get; set; }
        public Nullable<int> tipo { get; set; }
        public string tipo2 { get; set; }
        public string tipoDocumento { get; set; }
        public long numero { get; set; }
        public string numero2 { get; set; }
        public System.DateTime fecha { get; set; }
        public string fecha2 { get; set; }
        public decimal valor_total { get; set; }
        public string valor_total2 { get; set; }
        public string idencabezado2 { get; set; }
        public int bodega_id { get; set; }
        public string bodccs_nombre { get; set; }
        public Nullable<System.DateTime> fec_actualizacion { get; set; }
        public int tercero_id { get; set; }
        public string tercero_id2 { get; set; }
        public string doc_tercero { get; set; }
        public string tercero { get; set; }
        public string fecha_actualizacion { get; set; }
    }
}
