//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_promedio
    {
        public string codigo { get; set; }
        public short ano { get; set; }
        public short mes { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<decimal> Promedio_niif { get; set; }
        public Nullable<decimal> Promedio_aju { get; set; }
        public int bodega { get; set; }
    }
}
