//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_remisionClientes
    {
        public int idencabezado { get; set; }
        public long numero { get; set; }
        public System.DateTime fecha { get; set; }
        public string fecha2 { get; set; }
        public string nombreReferencias { get; set; }
        public string doc_tercero { get; set; }
        public string proveedor { get; set; }
        public string asesor { get; set; }
    }
}
