//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_solicitudes_traslados
    {
        public int Id { get; set; }
        public string numero { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public Nullable<int> Estado_atendido { get; set; }
        public string fecha2 { get; set; }
        public int Id_bodega_origen { get; set; }
        public string bodegaorigen { get; set; }
        public int Id_bodega_destino { get; set; }
        public string bodegadestino { get; set; }
        public string nombre_estado { get; set; }
        public string color { get; set; }
        public string listaReferencias { get; set; }
        public Nullable<long> numeroTraslado { get; set; }
        public string numero2 { get; set; }
        public string mensajeria_atentido { get; set; }
        public Nullable<int> fk_agendamiento { get; set; }
    }
}
