//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tramitadores
    {
        public int tramitador_id { get; set; }
        public string tramitador_documento { get; set; }
        public string tramitadorpri_nombre { get; set; }
        public string tramitadorseg_nombre { get; set; }
        public string tramitador_apellidos { get; set; }
        public string tramitador_celular { get; set; }
        public bool tramitador_estado { get; set; }
        public string tptramivh_nombre { get; set; }
    }
}
