//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ventas_repuestosGrafica
    {
        public int encab { get; set; }
        public int bodega { get; set; }
        public string bodccs_nombre { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<decimal> total_ventas { get; set; }
        public Nullable<int> numero_ventas { get; set; }
        public Nullable<decimal> Participacion { get; set; }
    }
}
