//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homer_MVC.IcebergModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFinancieraDatos
    {
        public int id { get; set; }
        public int financiera_id { get; set; }
        public Nullable<int> tercero_id { get; set; }
        public string financiera { get; set; }
        public string asesor { get; set; }
        public int numero { get; set; }
        public Nullable<decimal> valor_comision { get; set; }
        public Nullable<System.DateTime> fec_confirmacion { get; set; }
        public Nullable<System.DateTime> fec_facturacomision { get; set; }
    }
}
